### ISSUE TITLE
Operation canceled exception when trying to use AdminDeleteUserAsync

### ISSUE THREAD

**Issue by simax** [aws/aws-aspnet-cognito-identity-provider#100]
```
var deleteUserRequest = new AdminDeleteUserRequest { Username = username, UserPoolId = _poolId};
var config = new AmazonCognitoIdentityProviderConfig { RegionEndpoint = Amazon.RegionEndpoint.EUWest1 };
var adminDeleteUserResponse = await new AmazonCognitoIdentityProviderClient(config)
                                                        .AdminDeleteUserAsync(deleteUserRequest);
```
Executing the code above is throwing an exception (**"The operation was canceled."**) 

I wonder if this is related to [issue 41](https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/41)?  

I tried some of the advice mentioned on the other issue like passing an access key and secret (which I don't want to do anyway) and also adding the "AmazonCognitoPowerUser" policy to my IAM account but then I got a different exception stating:

`User: arn:aws:iam::123546789:user/xxxxxxx is not authorized to perform: cognito-idp:AdminDeleteUser on resource: arn:aws:cognito-idp:eu-west-1:123456789:userpool/eu-west-1_1xxxxx with an explicit deny" 
`

If the issues are related is there any ETA on a fix? If they're not, do you have any suggestions on how I could get this to work.

Thanks

**Comment by sstevenkang** [comment]
This seems to be IAM permission issue. Why do you think this is a bug in the library?

**Comment by simax** [comment]
Yep, you're right. After some further digging it was an IAM permission issue.
