### ISSUE TITLE
Authorization always fails with 404

### ISSUE THREAD

**Issue by jochencschmidt** [aws/aws-aspnet-cognito-identity-provider#101]
I've implemented the authorization exactly as described in the Readme, but when I use the [Authorize] attribute for any controller method, I always get the following error:

Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Information: Authorization failed.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker: Information: Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
Microsoft.AspNetCore.Mvc.ChallengeResult: Information: Executing ChallengeResult with authentication schemes ().
Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler: Information: AuthenticationScheme: Identity.Application was challenged.

Somehow it seems that the access token is not even validated. Any comments?

Here is are the relevant snippets from my startup.cs:

In ConfigureServices:

```
var cognitoIdentityProvider = new AmazonCognitoIdentityProviderClient((RegionEndpoint.EUCentral1);
            var cognitoUserPool = new CognitoUserPool("<MyUserPoolId>", "<MyClientId>", cognitoIdentityProvider);
            services.AddSingleton<IAmazonCognitoIdentityProvider>(cognitoIdentityProvider);
            services.AddSingleton(cognitoUserPool);
            services.AddCognitoIdentity();
```

In Configure:
`app.UseAuthentication();`

I'm using Amazon.AspNetCore.Identity.Cognito v1.0.0 and Amazon.Extensions.CognitoAuthentication v1.0.3

Thanks! Any help is appreciated.

**Comment by gilfoyle-predictile** [comment]
Me too! I found that this additional code allows the `[Authorize]` attribute work as expected.

```csharp
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
{
    options.Audience =  // UserPoolClientId
    options.Authority = // https://cognito-idp.<Region>.amazonaws.com/<UserPoolId>
});
```

**Comment by jochencschmidt** [comment]
> Me too! I found that this code is all that you need for the `[Authorize]` attribute to work as expected.
> 
> ```cs
> services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(options =>
> {
>     options.Audience =  // UserPoolClientId
>     options.Authority = // https://cognito-idp.<Region>.amazonaws.com/<UserPoolId>
> });
> ```

Thanks for the information. I'm not quite sure if this really solves the described problem. I think you can even remove the line services.AddCognitoIdentity(); completely and your solution would still work. It's just the standard implementation of an JWT bearer token for authentication/authorization. Can you use the cognito-specific features, such as [Authorize(Roles = "Admin")] with you solution?

**Comment by kawaic** [comment]
I am also having the same problem, it does not seem to be checking the bearer token at all.   Authentication works only when using cookies.  
Adding the following forces triggering of the JwtBearerHandler but fails
`            services
                .AddAuthentication(options =>
                {
                    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
                    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
                })
                .AddJwtBearer(options =>
                {
                    options.Audience = "<userPoolClientId>";
                    options.Authority = "https://cognito-idp.us-east-1.amazonaws.com/<userPoolId>";
                });`
`IDX10214: Audience validation failed. Audiences: '[PII is hidden]'. Did not match: validationParameters.ValidAudience:`

**Comment by foo1976** [comment]
I am also having the same problem.

**Comment by ashishdhingra** [comment]
Hi @jochencschmidt,

I came across the useful article [ASP.NET Core with AWS Lambda and Cognito](https://criticalhittech.com/2019/02/19/asp-net-core-with-aws-lambda-and-cognito/) which might be useful for configuring Cognito Group based authorization in an ASP.NET Core application. It has a section **Groups and Policies** which provides the following details to add a custom policy.

_You can use [Authorize] to ensure that only logged-in users can access the Page/Controller/Route. However you’d probably like more fine-grained control, so for that you can add users to Cognito Groups. On the ASP.NET Core app, those groups are sent as part of the user Claims. You can create authorization polices during the Startup.Configure method as follows:_
```C#
services.AddAuthorization(options =>
{
    options.AddPolicy("AdminOnly", policy =>
    policy.RequireAssertion(context =>
    context.User.HasClaim(c => c.Type == "cognito:groups" && c.Value == "Admin")));
});
```
_This creates a policy requiring the logged in user to be part of the Cognito group Admin. To use this on a Page/Controller/Route, refer to the policy name in the Authorize attribute:_
```C#
[Authorize(Policy = "AdminOnly")]
```

Article [Now generally available: the ASP.NET Core Identity Provider for Amazon Cognito](https://aws.amazon.com/blogs/developer/now-generally-available-the-asp-net-core-identity-provider-for-amazon-cognito/) also provides similar guidance.

Please let me know if this helps.

Thanks,
Ashish
