### ISSUE TITLE
Use Amazon Cognito with Amazon RDS

### ISSUE THREAD

**Issue by rajausman** [aws/aws-aspnet-cognito-identity-provider#102]
Hye ! I am new in AWS cognito and little bit confused while using aws-aspnet-cognito-identity-provider please help me out .
1) Is this identity only for giving access or permission to use other aws services after sign-in and sign-up feature or it will behave like asp.net core identity in which you can migrate your schema and tables are automatically generated in SQL Server ?
2) Can this identity provider migrate schema to Amazon RDS?

**Comment by assyadh** [comment]
Hi,

This Library will substitute the usual Microsoft SQL Server Identity tables (in conjunction with Entity Framework) with Amazon Cognito:

https://aws.amazon.com/cognito/?nc1=h_ls

Amazon Cognito lets you add user sign-up, sign-in, and access control to your web app and handles the user backend for you.

In addition, you can then retrieve AWS Credentials of logged in users to query other AWS Services if needed.

Hope this helps, feel free to reopen if needed.
