### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by edcastanohunter** [aws/aws-aspnet-cognito-identity-provider#103]
Hi, 

I am having the following error when try to run an asp.net core 3.0 app.

`System.TypeLoadException: 'Method 'NormalizeName' in type 'Amazon.AspNetCore.Identity.Cognito.CognitoKeyNormalizer' from assembly 'Amazon.AspNetCore.Identity.Cognito, Version=1.0.0.0, Culture=neutral, PublicKeyToken=885c28607f98e604' does not have an implementation.'

![image](https://user-images.githubusercontent.com/7706479/56972807-495e5800-6b31-11e9-82af-cab5ff471d92.png)
`

Could you guide me trough this?

Regards,
Ed

**Comment by edcastanohunter** [comment]
These are the nuget package versions that I am using.
![image](https://user-images.githubusercontent.com/7706479/56973128-d9040680-6b31-11e9-80e4-98fc2f8281d1.png)

**Comment by klaytaybai** [comment]
Hi @jpeddicord, could you please provide a stack trace?

**Comment by klaytaybai** [comment]
Hi @edcastanohunter, could you please provide a stack trace?

**Comment by edcastanohunter** [comment]
Of course,
`   at Microsoft.Extensions.DependencyInjection.CognitoServiceCollectionExtensions.InjectCognitoUser[TUser](IServiceCollection services, Action`1 identityOptions)
   at Microsoft.Extensions.DependencyInjection.CognitoServiceCollectionExtensions.AddCognitoIdentity(IServiceCollection services, Action`1 identityOptions, String prefix)
   at WebAdvert.Web.Startup.ConfigureServices(IServiceCollection services) in C:\WS1\AWS\WebAdvert.Web\WebAdvert.Web\Startup.cs:line 38`

**Comment by assyadh** [comment]
Hi,

Related to https://github.com/aspnet/AspNetCore/issues/8572

This looks like a breaking change on ASP.NET Core 3.0 preview 4, which you are running.

Thanks for reporting this, I will look into what's the best course of action

**Comment by edcastanohunter** [comment]
Thanks to you too for your support, I will keep an eye on this.

**Comment by flgatormike** [comment]
Is there any update on this? Or any work-around? Thanks!!

**Comment by arek159** [comment]
Same problem, looking for a solution 👍

**Comment by assyadh** [comment]
Hi,

This is not the only backward incompatible change coming with 3.0.  We are still weighing our options.

In the meantime can you guys share what are your use cases requiring the preview 3.0 of ASP.NET Core?

This may help our decision

**Comment by assyadh** [comment]
@flgatormike, the current workaround is to downgrade to 2.1. 3.0 is stil in dev preview.

**Comment by arek159** [comment]
> Hi,
> 
> This is not the only backward incompatible change coming with 3.0. We are still weighing our options.
> 
> In the meantime can you guys share what are your use cases requiring the preview 3.0 of ASP.NET Core?
> 
> This may help our decision

My company has started developing a new project and our customer wanted to use the newest libraries, that's the only reason of using 3.0. We have switched to .net core 2.2 and it works :)

**Comment by flgatormike** [comment]
We are currently using it with .net core 2.2 with no issues. We will be starting some new projects soon that will probably use the latest .net core and will have to make a decision at that time whether to continue using Cognito, I guess. Thanks.

**Comment by assyadh** [comment]
Hi,

I still have this issue in my radar, we will support .NET Core 3.0 when it will be GA in addition to netstandard2.0

H.

**Comment by chuckconway** [comment]
I'm working with 3.0 Preview 8 and I'm encountering this issue. Is there any plans to support .net standard 2.1?

**Comment by assyadh** [comment]
Yes, I will get that merged this week, stay tuned!!

**Comment by assyadh** [comment]
Another breaking change: https://github.com/aspnet/Announcements/issues/374

**Comment by assyadh** [comment]
Hi everyone,

Here is a preview build of the library supporting the ASP.NET Core 3.0 target.

We are trying to get the official 1.0.3 out for the GA of .NET Core 3.0

[Amazon.AspNetCore.Identity.Cognito.1.0.3.nupkg.zip](https://github.com/aws/aws-aspnet-cognito-identity-provider/files/3517828/Amazon.AspNetCore.Identity.Cognito.1.0.3.nupkg.zip)


Let me know if that unblocks you or not.

Thanks!

**Comment by bertrandm** [comment]
@assyadh The version you posted works for me on DotNet 3.9 SDK version dotnet-sdk-3.0.100-preview8-013656. Do you have an ETA when it will be available on Nuget?

**Comment by kehoej** [comment]
@assyadh I have the same question as @bertrandm... I'm on 3.0.0-preview8 and 1.0.3 works for me, but do you know when it will be available via nuget?

**Comment by rushdy20** [comment]
taking the package from  Amazon.AspNetCore.Identity.Cognito.1.0.3.nupkg.zip worked for me but please update once this is available get directly from nuget manager

**Comment by bertrandm** [comment]
@assyadh Would it be possible for you to at least give an estimation when you are likely to create a nuget package. I am in the process of trying to build a version of the application and my build process is broken because it is expecting a nuget package. I need to plan accordingly.

**Comment by adrianofo** [comment]
@assyadh Hello Hamza. We are upgrading our current apps to use the new Asp.Net Core 3.0. Any ETA?

**Comment by normj** [comment]
Sorry everybody for the delay, we are working to get the the 3.0 version out. We have had to juggle around a bit of resources lately which has caused the delay but it is high on our list to get you all unblocked and the the 3.0 version out.

**Comment by TNadir** [comment]
> Hi everyone,
> 
> Here is a preview build of the library supporting the ASP.NET Core 3.0 target.
> 
> We are trying to get the official 1.0.3 out for the GA of .NET Core 3.0
> 
> [Amazon.AspNetCore.Identity.Cognito.1.0.3.nupkg.zip](https://github.com/aws/aws-aspnet-cognito-identity-provider/files/3517828/Amazon.AspNetCore.Identity.Cognito.1.0.3.nupkg.zip)
> 
> Let me know if that unblocks you or not.
> 
> Thanks!

I can't find Amazon.AspNetCore.Identity.Cognito.1.0.3 on nuget .
could you please provide me with a Link.
I tried to download and install it requires ID
![image](https://user-images.githubusercontent.com/34626886/68217543-d6f49600-fff3-11e9-9540-b36f9951de9d.png)
how can I install that new pkg? 
Thanks

**Comment by MarkStruik** [comment]
i am using the 1.0.3 package but it is not working for me:
Am i missing something?? i am using the 

Fiddler output:
![image](https://user-images.githubusercontent.com/8427513/68391367-c06f4b80-0167-11ea-9757-b1278d716c27.png)

sample code:
![image](https://user-images.githubusercontent.com/8427513/68391409-dbda5680-0167-11ea-982c-52cd3a91f3b2.png)

appsettings.json:
![image](https://user-images.githubusercontent.com/8427513/68391450-f3194400-0167-11ea-88d6-e4170ba0cf3b.png)

**Comment by assyadh** [comment]
Hi @MarkStruik , you can have a look at the docs folder here. The best way to use the library is to use the AWS Toolkit for Visual Studio. It will set up all the required tooling for you.

By the way, the 1.03 version is out on NuGet and supports .NET Core 3.0

https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/1.0.3

Resolving.

**Comment by MarkStruik** [comment]
Ok perfect 👌 I got it to work through debugging errors and resolving it. Good to see I can use the official nugget now. Thanks for the update!


Op 22 nov. 2019 om 23:33 heeft Hamza Assyad <notifications@github.com> het volgende geschreven:

﻿

Hi @MarkStruik<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarkStruik&data=02%7C01%7C%7C59757615ac6940979b5308d76f9c0c05%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637100588309992097&sdata=nPuQK5Pe1%2FCRrAxkdl6sKEnD%2FaKjaR9N7v4EVGm9ah8%3D&reserved=0> , you can have a look at the docs folder here. The best way to use the library is to use the AWS Toolkit for Visual Studio. It will set up all the required tooling for you.

By the way, the 1.03 version is out on NuGet and supports .NET Core 3.0

https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/1.0.3<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.nuget.org%2Fpackages%2FAmazon.AspNetCore.Identity.Cognito%2F1.0.3&data=02%7C01%7C%7C59757615ac6940979b5308d76f9c0c05%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637100588310002107&sdata=Fdl4Xj0O8RyJbxKq7M8Z2El7gShJo4CVrS0XM5ARdY8%3D&reserved=0>

Resolving.
