### ISSUE TITLE
Parsing claims from Cognito User Pool Authorizer

### ISSUE THREAD

**Issue by LUS1N** [aws/aws-aspnet-cognito-identity-provider#104]
Hi,

In my architecture the API calls are coming in through API Gateway, where a CUP lambda authorizer is invoked for token validation and then the request is proxied to an ECS container running an ASP.NET Core 2.1 app.

How would I reach the claims injected by the authorizer?

When running asp.net core on lambda they would get injected together with the event, but since this is running on Kestrel that doesn't happen. 

Would using this library solve this problem? Seems like it would be the right place for that.

I'd prefer to keep using the lambda authorizer to validate the tokens, cause I have multiple backends and it provides caching as well as other benefits. 

Need to be able to read the claims though.

**Comment by assyadh** [comment]
I am not sure this library would solve your problem. This library substitute SQL Server for Amazon Cognito inside a .NET Core web app for authentication purposes
