### ISSUE TITLE
verifying emails

### ISSUE THREAD

**Issue by ghendo** [aws/aws-aspnet-cognito-identity-provider#106]
I am creating a new user programatically
var result = await _userManager.CreateAsync(user).ConfigureAwait(false);
and I would expect a "verify email" email with token to be sent but none is sent.
Do I need to trigger this?

**Comment by klaytaybai** [comment]
Can you try SendEmailConfirmationTokenAsync?

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/3097bafe2d73f58caef01a34cc55218dcc8e6278/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L438

**Comment by assyadh** [comment]
Hi,

The token is automatically sent to the provided attributes (email or phone) to the CreateAsync method.

As klaytaybai said, if for some reason you do not receive it, you can use SendEmailConfirmationTokenAsync to resend it.

This is described in the docs folder.

**Comment by Salcave** [comment]
Hello, I've run into a similar issue. I have a user pulled form my user manager, and then check to see if the email has been verified. When it has not, I'd like for a confirmation token to be sent to the user's email. Below is a snippet of the code that I'm using:
```
                CognitoUser user = await _userManager.FindByEmailAsync(Input.Email);

                if (!(await _userManager.IsEmailConfirmedAsync(user)))
                {
                    await _userManager.SendEmailConfirmationTokenAsync(user);
                    return RedirectToPage("/ConfirmEmail");
                }
```
On execution, though, I get the following error when I step into the SendEmailConfirmationTokenAsync method:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.AspNetCore.Identity.Cognito.CognitoUserStore`1.GetUserAttributeVerificationCodeAsync(TUser user, String attributeName, CancellationToken cancellationToken)
```

**Comment by klaytaybai** [comment]
Hi @Salcave, it may be that your user is not logged in, which is a prerequisite of GetUserAttributeVerificationCodeAsync and, by extension, SendEmailConfirmationTokenAsync.  Could you please verify that the user is logged in and let us know if that works once that's true?

**Comment by klaytaybai** [comment]
@ghendo, you may also be having problems if you are verifying both the email and phone number. 

Per this documentation on [Configuring Email and Phone Verification](https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/user-pool-settings-email-phone-verification.html),

> If a user signs up with both a phone number and an email address, and your user pool settings require verification of both attributes, a verification code is sent via SMS to the phone. The email address is not verified, so your app needs to call GetUser to see if an email address is awaiting verification. If it is, the app should call GetUserAttributeVerificationCode to initiate the email verification flow and then submit the verification code by calling VerifyUserAttribute.

**Comment by Salcave** [comment]
Hi @klaytaybai,

Before checking for email confirmation I have the user signed in through the manager and make sure it's successful before checking if their email is confirmed

                var result = await _signInManager.PasswordSignInAsync(Input.UserName, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    if (!(await _userManager.IsEmailConfirmedAsync(user)))
                    {
                        _logger.LogWarning("User has not verefied their changed email.");
                        await _userManager.SendEmailConfirmationTokenAsync(user);
                        return RedirectToPage("/ConfirmEmail");
                    }
                }

In my code I'm only verifying the user's email and on my pool I don't require phone number verification

**Comment by ashishdhingra** [comment]
Hi @ghendo,

Good afternoon.

I was going through the issue backlog and came across this one. Please let me know if you need further guidance or if this issue could be closed.

Thanks,
Ashish

**Comment by MarneeDear** [comment]
I had this problem too. I had to call `signInManager.SignInAsync(curUser, true)` before `userManager.IsEmailConfirmedAsync(curUser)`

**Comment by MarneeDear** [comment]
In my setup, if I have my User Pool configured liked this: 
![image](https://user-images.githubusercontent.com/5660628/93339243-2f81eb80-f7e0-11ea-976c-bcd749076d56.png)

And the user fails to verify email when changing an email. They cannot do it later because they cannot sign in. And they need to be signed in in order to resend an email confirmation. `signInManager.SignInAsync(curUser, true)` does not work in this setting. Please tell me there is a way to send an email verification token when the user is not signed in.

**Comment by ashishdhingra** [comment]
Hi @MarneeDear,

I didn't got a chance to have a look at it yet. Please confirm if phone number doesn't work for authentication.

Thanks,
Ashish

**Comment by MarneeDear** [comment]
I will try. We do plan on using phone number for sign on but not at the current time.

**Comment by ashishdhingra** [comment]
@MarneeDear Thanks for your response. I think the possibility to use either of username and phone number was included so that change in email does not prevent user from logging in. Please also refer https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/67#issuecomment-692379506 where similar issue was reported. Feel free to open new issue in case there is any problem using phone number option.

@ghendo Please let me know if you need further guidance or if this issue could be closed.

Thanks,
Ashish

**Comment by MarneeDear** [comment]
I think I understand. Please feel free to close.
