### ISSUE TITLE
What's the migrations for in the sample project ?

### ISSUE THREAD

**Issue by oooolivierrrr** [aws/aws-aspnet-cognito-identity-provider#107]
Hi,

I was under the impression that the cognito service is handling everything (data wise). Roles, claims, users, etc... all datas that usually went into a local database.

Also, I was wondering if it was possible to reuse the identity library that come with asp.net core instead of using what's in the sample. There's some minor differences between the two and I was wondering why (for example) "cognitouser" does not inherit from "identityuser".

**Comment by assyadh** [comment]
Hi,

This is the goal of this library, it will substitute cognito to sql server.

Please have a look at the docs, this will probably help: https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/docs

Also, The CognitoUser class brings more features than the IdentityUser class, and to be able to dependency inject it, it was a better design to force a Cognito specific class.

**Comment by kewur** [comment]
where on the doc are you referring to? I too thought that this library would be circumventing all the sql database stuff. Guess I should be using an openid client instead?
