### ISSUE TITLE
FindByLoginAsync - External Providers

### ISSUE THREAD

**Issue by jhakooz** [aws/aws-aspnet-cognito-identity-provider#108]
AWS Cognito Provider does not appear to include the external provider functionality (Sign in with Google, Facebook, etc...)

When attempting to use ExternalLoginSignInAsync I get the following error...

> NotSupportedException: Store does not implement IUserLoginStore<TUser>.

I can provide a more detailed error if that would help.

**My question...**
Are there any plans to include FindByLoginAsync so we can use the cognito provider with external logins? That would be awesome!!

PS, thank you all for the great work you've done so far.

**Comment by assyadh** [comment]
Hi,

Indeed it is not supported in V1, We are thinking of including this in the next versions, but a design decision will need to be made between how Cognito handles the external providers VS how Identity also handles them.

**Comment by jhakooz** [comment]
I think that functionality would be incredibly useful and hope you decide to implement it. Again, thanks for all the work you've done!

**Comment by harsimranb** [comment]
This functionality would be very useful to us as well - it helps us build and control a custom auth flow for our asp.net web app.

**Comment by fracampit** [comment]
I guess if there are no updates on this 3 years later you are not going to implement this, right?
