### ISSUE TITLE
Unable to see Enabled status on CognitoUser

### ISSUE THREAD

**Issue by blaisealicki** [aws/aws-aspnet-cognito-identity-provider#110]
I'm porting an existing app into Cognito and have a requirement for administrators to be able to enable and disable accounts.  I'm looking at the results of GetUsersAsync and it looks like the List<UserType> Users on the response have the Enabled field, but that isn't carried onto CognitoUser. Is there a way to read and write to the Enabled field that I am missing?

**Comment by klaytaybai** [comment]
You should be able to do this by using the AdminEnableUser and AdminEnableUser methods on the AmazonCognitoIdentityProviderClient found in AWSSDK.CognitoIdentityProvider.

**Comment by blaisealicki** [comment]
That works for me, thanks. I would like to see the Enabled property carried over to the CognitoUser and populated by default when calling GetUsersAsync, but I'm able to work around it.

**Comment by assyadh** [comment]
Hi @blaisealicki, Feel free to submit a PR, I would be happy to review it and get it merged.

H.
