### ISSUE TITLE
Registration example not working

### ISSUE THREAD

**Issue by cmcclellen** [aws/aws-aspnet-cognito-identity-provider#112]
https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/d40b035c6661f6def500f9521bf80b9e8e845eea/samples/Samples/Areas/Identity/Pages/Account/Register.cshtml.cs#L79

In the registration example, it tries to sign you in after createuserasync, but the login fails because the email is unconfirmed, causing an exception before getting to confirmemail.

I didn't see a way to allow login with unconfirmed emails.  I ended up working around it by passing the login name to the confirm page, and using a FindByXXXAsync call to lookup the user and process the confirm.

**Comment by assyadh** [comment]
Hi,

Thanks for reporting this.

Can you share your user pool settings around user confirmation and logging?

This has to do with how user pools are configured.

**Comment by keithbeller** [comment]
I'm having an issue with registration too.  I get an "AmazonCognitoIdentityProviderException: The security token included in the request is invalid."

I configured my cognito app using the step provided in this quick video from AWS.
https://www.youtube.com/watch?v=LcD_-p1gCww
