### ISSUE TITLE
Password Validation for special symbols is bugged

### ISSUE THREAD

**Issue by todor-mutafov** [aws/aws-aspnet-cognito-identity-provider#116]
The condition in the following line doesn't look right to me:
https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/d40b035c6661f6def500f9521bf80b9e8e845eea/src/Amazon.AspNetCore.Identity.Cognito/CognitoPasswordValidator.cs#L66

When the validator requires special symbols, this condition doesn't allow passwords that start with special symbols, since then `IndexOfAny` returns `0` and the validator returns `PasswordRequiresNonAlphanumeric` as an error.

The condition should be `password.IndexOfAny(CognitoSymbols) >= 0;` instead, or if this a feature it should be clearly stated that passwords must not start with special symbols to be considered valid.

Thanks.

**Comment by klaytaybai** [comment]
Thanks.  I believe you are right.

**Comment by assyadh** [comment]
Hi,

Version 1.0.2 should be available shortly and solves the problem.

Thanks for reporting it.

Hamza.
