### ISSUE TITLE
OpenIdConnectParameterNames.ExpiresIn property is null

### ISSUE THREAD

**Issue by genii90** [aws/aws-aspnet-cognito-identity-provider#121]
After a user has been logged in, I attempt to get the value of:
`HttpContext.GetTokenAsync(OpenIdConnectParameterNames.ExpiresIn) `

which always returns null.

However the following returns a value:
`HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken)`

I would like to check whether an access token is expired before trying to use it. How can I retrieve the value of HttpContext.GetTokenAsync(OpenIdConnectParameterNames.ExpiresIn)?

**Comment by klaytaybai** [comment]
If you have your CognitoUser, you can get the expiration time via CognitoUser.SessionTokens.ExpirationTime

**Comment by genii90** [comment]
Thanks. It worked.
