### ISSUE TITLE
"UserPoolClientSecret" should be optional

### ISSUE THREAD

**Issue by Fydar** [aws/aws-aspnet-cognito-identity-provider#124]
### Expected Result

The `IConfiguration` value `AWS:UserPoolClientSecret` should be optional.

Using the environment variables I can access my user pool securely without using the `AWS:UserPoolClientSecret`, rendering it redundant in many setups.

### Actual Result

When the configuration value is not supplied, I receive the following exception.

```
CognitoConfigurationException: The UserPoolClientSecret key/value pair is missing or empty in the IConfiguration instance
```

### Work-Around

Instead of supplying this in the configuration I used the following code:

```csharp
const string PoolId = "#########_#########";
const string ClientId = "#########################";

var provider = new AmazonCognitoIdentityProviderClient ();
var cognitoUserPool = new CognitoUserPool (PoolId, ClientId, provider);

services.AddSingleton<IAmazonCognitoIdentityProvider> (provider);
services.AddSingleton (cognitoUserPool);

services.AddCognitoIdentity ();
```

### Using Packages

```xml
<PackageReference Include="Amazon.Extensions.CognitoAuthentication" Version="1.0.3" />
<PackageReference Include="Amazon.AspNetCore.Identity.Cognito" Version="1.0.3" />
<PackageReference Include="AWSSDK.CognitoIdentity" Version="3.3.100.72" />
<PackageReference Include="AWSSDK.CognitoIdentityProvider" Version="3.3.102.57" />
```

**Comment by klaytaybai** [comment]
Agreed.  Since this is optional, we need to make it optional here too.  Thanks.

**Comment by ashishdhingra** [comment]
This is fixed in [Amazon.AspNetCore.Identity.Cognito 2.0.3](https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/2.0.3)
