### ISSUE TITLE
resend temporary password

### ISSUE THREAD

**Issue by ghendo** [aws/aws-aspnet-cognito-identity-provider#125]
If email confirmation is required and a temporary password has been sent then deleted by the user how can I trigger a new temporary password to be sent

**Comment by klaytaybai** [comment]
Hi @ghendo, you can do an AdminCreateUserRequest and set the MessageAction to RESEND.  https://github.com/aws/aws-sdk-net/blob/966617d346169e89a693dae74c5eec5cda0551b2/sdk/src/Services/CognitoIdentityProvider/Generated/Model/AdminCreateUserRequest.cs#L122-L130.
