### ISSUE TITLE
Question: Setup CognitoRole?

### ISSUE THREAD

**Issue by DragonMastery** [aws/aws-aspnet-cognito-identity-provider#127]
How exactly do I set my project up so that CognitoRole works? Specifically the ApplicationDbContext....

**Comment by klaytaybai** [comment]
Hi @DragonMastery, could you please review this [documentation](https://aws.amazon.com/blogs/developer/introducing-the-asp-net-core-identity-provider-preview-for-amazon-cognito) and let us know if you need further guidance around this?

**Comment by DragonMastery** [comment]
Well, to be honest the documentation does not help very much with explaining how the Role Service works. So I read through the source code and now I get it. You are using Cognito Groups as Roles. It would be nice if that were a little more clarified somewhere, because I really did not get that until I read through the source code. It might help if it were expanded on in [HERE](https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/docs/7-User%20Roles.md)
In essence the Roles have nothing to do with the ApplicationDbContext because the are not stored in the database.

**Comment by assyadh** [comment]
Any reason why you are mentioning ApplicationDbContext? We don't use it anymore in this library. 

Here is how we use Roles in this library:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/docs/7-User%20Roles.md

Roles are just mapped to a group you create in cognito.

**Comment by DragonMastery** [comment]
Thats literally what I just wrote.... with the same link...

**Comment by assyadh** [comment]
Yes, the sample has the old EF code, but it is swapped with the Cognito access layer.

Thanks for the feedback, made it more clear on the docs.

I will close this, let me now if you still have questions.
