### ISSUE TITLE
Change the Cognito access key and secret after startup, shared instance

### ISSUE THREAD

**Issue by MarneeDear** [aws/aws-aspnet-cognito-identity-provider#130]
I have a client where their Cognito instance is in a different account than the EC2 instance where the app runs. They asked AWS support and they suggested to call AssumeRole to get credentials to access Cognito.

I think I can do this at startup, but because the credentials expire after one hour, I would have to reset them all the time. Is it possible to do this after startup? For example, in a controller?

Thank you.

Here is what I got from AWS Support:

> Please keep in mind that the code running in your EC2 instance would have to make the AssumeRole API call to STS to assume the role present in Cognito's account which would return temporary security credentials. You would have to construct the Cognito service object using these credentials that comprises of a secret key, access key and session token to be able to make Cognito API calls. 

**Please keep in mind that the temporary security credentials are valid by default for 1 hour**. 

> You can extend this for a period of upto 12 hours by specifying the DurationSeconds parameter to the AssumeRole API call from your code. If you're making use of the Python Boto3 SDK, you can specify this parameter as illustrated here:

>  In your web app where you are making the API Call to Cognito user pool in another account, create a AssumeRole [1] API Call and get credentials. Then using those credentials initiate the cognito-idp client and make the API call.
> 
> For example, I used the below python code to connect to a userpool in another account using :
> 
```
> import json
> import boto3
> 
> #client = boto3.client('cognito-idp')
> sts = boto3.client('sts')
> 
> response = sts.assume_role(RoleArn='arn:aws:iam::<ANOTHER-ACC_ID>:role/cognito-cross-account-role', RoleSessionName='CognitoSec',ExternalId='CogExternal')

> assumed_credentials = response['Credentials']
> 
> client = boto3.client(
>         'cognito-idp',
>         aws_access_key_id = assumed_credentials['AccessKeyId'],
>         aws_secret_access_key = assumed_credentials['SecretAccessKey'],
>         aws_session_token = assumed_credentials['SessionToken']
>     )
```
> 
> # TODO implement
> response = client.list_users(
> UserPoolId='<USERPOOL NAME>)
> 
> Upon running my python file, I was able to run listusers on Cognito instance in another account. You may base your code on the above approach.
> 
> I hope this helps. In case of any queries, please feel free to get back to me.

**Comment by klaytaybai** [comment]
Hi @MarneeDear, good question.  I think it should be possible.  Try doing something like this:

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    // Adds your own instance of Amazon Cognito clients 
    // cognitoIdentityProvider and cognitoUserPool are variables you would have instanciated yourself
    services.AddSingleton<IAmazonCognitoIdentityProvider>(new AssumeRoleCognitoIdentityProvider(...));
    services.AddSingleton<CognitoUserPool>(cognitoUserPool);

    // Adds Amazon Cognito as Identity Provider
    services.AddCognitoIdentity();
    ...
}
```
```    
using System.Threading;
using System.Threading.Tasks;
using Amazon.CognitoIdentityProvider;
using Amazon.CognitoIdentityProvider.Model;
using Amazon.Runtime;

namespace CognitoClientSwitch
{
    public class AssumeRoleCognitoIdentityProvider : IAmazonCognitoIdentityProvider
    {
        private IAmazonCognitoIdentityProvider client;
        private AssumeRoleAWSCredentials assumeRoleAWSCredentials;
        private ImmutableCredentials currentCredentials;

        public AssumeRoleCognitoIdentityProvider(AssumeRoleAWSCredentials assumeRoleAWSCredentials)
        {
            this.assumeRoleAWSCredentials = assumeRoleAWSCredentials;
            this.currentCredentials = assumeRoleAWSCredentials.GetCredentials();
            this.client = new AmazonCognitoIdentityProviderClient(assumeRoleAWSCredentials);
        }

        public IClientConfig Config => client.Config;

        public IAmazonCognitoIdentityProvider Client
        {
            get
            {
                if (!assumeRoleAWSCredentials.GetCredentials().Equals(currentCredentials)) {
                    client = new AmazonCognitoIdentityProviderClient(assumeRoleAWSCredentials);
                }

                return client;
            }
        }

        public Task<AddCustomAttributesResponse> AddCustomAttributesAsync(AddCustomAttributesRequest request, CancellationToken cancellationToken = default)
        {
            return Client.AddCustomAttributesAsync(request, cancellationToken);
        }

        public Task<AdminAddUserToGroupResponse> AdminAddUserToGroupAsync(AdminAddUserToGroupRequest request, CancellationToken cancellationToken = default)
        {
            return Client.AdminAddUserToGroupAsync(request, cancellationToken);
        }
...
```

**Comment by MarneeDear** [comment]
Thank you, I will try this.
