### ISSUE TITLE
AWS Lambda Serverless - Antiforgery token validation failed. The antiforgery token could not be decrypted.

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-aspnet-cognito-identity-provider#131]
We're trying to do this with AWS Lambda Serverless and keep running into the error

Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.AutoValidateAntiforgeryTokenAuthorizationFilter: Antiforgery token validation failed. The antiforgery token could not be decrypted.

I suspect it is because the Post is running on a different server?

We've tried the <machineKey> work-around in web.config and the IgnoreAntiforgeryTokenAttribute work-around.

Anyone else gotten this working?

Any thoughts?

**Comment by normj** [comment]
The Antiforgery framework in ASP.NET Core uses its underlying Data Protection framework that generates encryption keys as needed. By default the keys are persisted in memory or the file system. If you use our [AWS Systems Manager ASP.NET Core Data Protection Provider](https://github.com/aws/aws-ssm-data-protection-provider-for-aspnet) package it will use AWS Systems Manager to keep the encryption key in sync for all of the compute environment running the ASP.NET Core application.

**Comment by hounddog22030** [comment]
You rock (as usual)!
