### ISSUE TITLE
Getting IdToken

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-aspnet-cognito-identity-provider#132]
We would like to be able to get the user's SessionToken.IdToken so we can use it call API Gateway for RESTful API calls.

I can get it by "authenticating twice", using the same method as we do in a desktop app as shown below as a modification to the sample asp.net Core app's Login page - OnPostAsync.

Is there a better way to do this?

`            try
            {
                returnUrl = returnUrl ?? Url.Content("~/Index");

                if (ModelState.IsValid)
                {
                    var result = await _signInManager.PasswordSignInAsync(Input.UserName, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                    // begin modification to sample
                    var provider = new AmazonCognitoIdentityProviderClient(new AnonymousAWSCredentials(), RegionEndpoint.USEast1);

                    var clientId = _configuration["AWS:UserPoolClientId"];
                    var clientSecret = _configuration["AWS:UserPoolClientSecret"];
                    var userPool = new CognitoUserPool(_configuration["AWS:UserPoolId"], clientId, provider, clientSecret);
                    CognitoUser user = new CognitoUser(Input.UserName, clientId, userPool,provider,clientSecret);
                    var response = await user.StartWithSrpAuthAsync(new InitiateSrpAuthRequest() {Password = Input.Password}).ConfigureAwait(false);
                    Debug.Write(user.SessionTokens.IdToken);
                    // end modification to sample
`

**Comment by normj** [comment]
Here is a snippet recently wrote for a the demo I'm trying to together for re:Invent. You can ignore _authenticationStateProvider. Basically `user` is the ClaimsPrincipal you can find from the HttpContext object.

```csharp
private async Task<HttpClient> ConstructHttpClient()
{
    var authState = await this._authenticationStateProvider.GetAuthenticationStateAsync();
    var user = authState.User;
    if(!user.Identity.IsAuthenticated)
        throw new NoIdTokenException();

    var userId = this._cognitoUserManager.GetUserId(user);
    if (string.IsNullOrEmpty(userId))
        throw new NoIdTokenException();

    var cognitoUser = await this._cognitoUserManager.FindByIdAsync(userId);
    if (string.IsNullOrEmpty(cognitoUser?.SessionTokens.IdToken))
        throw new NoIdTokenException();


    var httpClient = new HttpClient();
    httpClient.DefaultRequestHeaders.Authorization = AuthenticationHeaderValue.Parse($"bearer {cognitoUser.SessionTokens.IdToken}");


    return httpClient;
}   
```
