### ISSUE TITLE
Trying to add Google and LWA authentication

### ISSUE THREAD

**Issue by slackjawedyokel** [aws/aws-aspnet-cognito-identity-provider#134]
I've set up Google and Login With Amazon integration with my Cognito user pool and now I'm trying to get these identity providers reflected in the UI of the sample code to verify that everything is working as expected.  I've added Google with the below code, and while a button shows up in the UI after I execute this code when I click on the button it just seem to post-back rather than re-directing to Google (as indicated [here](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/social/google-logins?view=aspnetcore-3.0)).  Is this the proper way to add additional providers or should I be adding login buttons manually as described [here](https://developer.amazon.com/docs/login-with-amazon/add-a-button-web.html) in the LWA docs?

 `services.AddAuthentication().AddGoogle(options =>
                {
                    options.ClientId = Configuration["auth:google:clientid"];
                    options.ClientSecret = Configuration["auth:google:clientsecret"];
                });`

I'm sure I'm doing something stupid here but any help pointing me in the right direction would be appreciated.

**Comment by klaytaybai** [comment]
The services.AddAuthentication code should be the right approach.  I need to look into this more, but I think this library is still lacking the support for adding third party authentication.  I'll try to follow up on this soon.

**Comment by slackjawedyokel** [comment]
Is there anything that I can do to help get this issue resolved?

**Comment by hounddog22030** [comment]
+1

**Comment by hounddog22030** [comment]
I'd really like to get this going?  Can you provide some guidance and perhaps I can make a PR?

**Comment by hounddog22030** [comment]
?

**Comment by ashishdhingra** [comment]
Hi @slackjawedyokel,

Good afternoon.

I was going through the issue backlog and came across this guidance question. Following articles might be helpful in setting up Google as identity provider using Cognito:

- [https://developerhandbook.com/aws/how-to-use-aws-cognito-with-net-core/](https://developerhandbook.com/aws/how-to-use-aws-cognito-with-net-core/) 

- [How do I set up Google as a federated identity provider in an Amazon Cognito user pool?](https://aws.amazon.com/premiumsupport/knowledge-center/cognito-google-social-identity-provider/)

Please let me know if this helps and if this issue could be closed.

Thanks,
Ashish
