### ISSUE TITLE
ResourceNotFoundException: User pool us-east-2_<id> does not exist.

### ISSUE THREAD

**Issue by Heinicke** [aws/aws-aspnet-cognito-identity-provider#135]
Im trying to get authentication working and I keep getting this error every time I try to log in. It claims the pool does not exist. Ive checked and triple checked my settings to ensure they are correct. What am I doing wrong?

I have omitted the ID in the below exception:

ResourceNotFoundException: User pool us-east-2_<id> does not exist.

**Comment by klaytaybai** [comment]
Hi @Heinicke, the most likely answer is that your credentials are configured for a region other than us-east-2 when making your calls to Cognito.  Can you please check your app settings (probably development) to see if another region is specified there?  If you don't specify a region there, please try to identify where in the [credentials profile chain](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/net-dg-config-creds.html) your region is being set.  If after doing this or setting break points and you still think your code is using a us-east-2 client, please let us know so we can continue to investigate.  Thanks.

**Comment by Heinicke** [comment]
Thanks so much for the reply. I will continue looking into the credentials profile chain. I have specified the settings in app settings show below. Is there anything further needed to get this connection working correctly? Does it need/use whatever is configured for the access key and secret access key? Thanks!
![image](https://user-images.githubusercontent.com/2421001/68212942-9de30400-ffa8-11e9-9db2-9f763f1d763a.png)

**Comment by klaytaybai** [comment]
Thanks for the response, @Heinicke.  If you are still having this problem, could you please add a call stack?

**Comment by Heinicke** [comment]
@klaytaybai Yes I can, Here is the call stack:

[stacktrace.txt](https://github.com/aws/aws-aspnet-cognito-identity-provider/files/3832888/stacktrace.txt)

**Comment by ashishdhingra** [comment]
Hi @Heinicke,

I do not see any movement on this issue for quite long. Please let me know if this is still an issue (if yes, please provide the sample code) or if this issue could be closed.

Thanks,
Ashish

**Comment by Heinicke** [comment]
Its not applicable but considering I asked another question....and never got a response not sure why you would assume it can be closed. I have since went with a different solution

**Comment by bmarshalsea** [comment]
After going around in circles for an hour on this.
CHECK YOUR AWS_ACCESS_KEY/SECRET - ensure this is the correct credentials for:
1) The AWS Account with the Resource you're looking for.
2) The IAM has permissions to access to the Resource you're looking for.
