### ISSUE TITLE
Amazon.CognitoIdentityProvider.Model.ResourceNotFoundException: User pool client {id} does not exist.

### ISSUE THREAD

**Issue by alex-bello** [aws/aws-aspnet-cognito-identity-provider#136]
I have a small React SPA with a WebAPI backend that uses Cognito as the Identity Provider. This application was working without issue a few weeks ago. Not sure when it happened, but all of a sudden, the `signin`endpoint no longer works. I get the error provided above.

I checked that settings multiple times and verified from the CLI that the `ClientId` and `UserPoolId` both exist and are visible to the IAM user. I also made sure that the user exists in the user pool and is confirmed.

Has something changed in the SDK or endpoint that I am not aware of?

Thanks in advance.

**Comment by klaytaybai** [comment]
Hi @alex-bello, can you please confirm that nothing changed in your credentials and client creation?  How do you create your credentials and client?  There is a chance that for some reason a different region is being used than what you were originally using.

**Comment by alex-bello** [comment]
I thought that might have been an issue, so I created a new IAM user with all Cognito rights granted and updated the `AWS_SECRET_KEY` and `AWS_SECRET_KEY_ID` to match. That didn't work, so I created a new app client and updated the settings as well. 

To be completely sure, I changed both values to my personal secret and secret key (I am an admin) and then just for the sake of overkill, I erased and recreated my CLI credentials if for some reason .NET was ignoring the env variables provided via launch.json and using my globals instead.

The register action works just fine and is as follows:

```c#
[HttpPost]
[Route("register")]
[AllowAnonymous]
[ProducesResponseType(StatusCodes.Status200OK)]
[ProducesResponseType(StatusCodes.Status400BadRequest)]
public async Task<ActionResult<string>> Register(RegisterUser user)
{
    var cognito = new AmazonCognitoIdentityProviderClient(RegionEndpoint.USEast1);
    var request = new SignUpRequest
    {
        ClientId = _clientId, //DI Injected from IOptions in Controller
        Password = user.Password,
        Username = user.Email
    };

    request.UserAttributes.Add(new AttributeType { Name = "email", Value = user.Email });
    var response = await cognito.SignUpAsync(request);

    return Ok()
}
```

The SignIn action, which was working just fine a few weeks ago but is now giving me problems is as follow:

```c#
[HttpPost]
[Route("signin")]
[AllowAnonymous]
public async Task<ActionResult<string>> SignIn(SignInUser user)
{
    var cognito = new AmazonCognitoIdentityProviderClient(RegionEndpoint.USEast1);

    var request = new AdminInitiateAuthRequest
    {
        UserPoolId = _poolId, // Obtained from IOptions by DI during Controller Construction
        ClientId = _clientId, // Obtained from IOptions by DI during Controller Construction
        AuthFlow = AuthFlowType.ADMIN_NO_SRP_AUTH
    };

    request.AuthParameters.Add("USERNAME", user.Email);
    request.AuthParameters.Add("PASSWORD", user.Password);

    var response = await cognito.AdminInitiateAuthAsync(request);

    return Ok(response.AuthenticationResult.IdToken);
}
```

**Comment by sohaibmaroof** [comment]
I am having exactly the same problem, can we please open this issue?

**Comment by ihiresolutions** [comment]
@klaytaybai Hi. I apologize for rebooting this issue after such a long time. Turns out I have a similar issue. I got the ClientId and UserPool Id from the Cognito Console and am hard-coding it to test, yet the error indicates that the user pool client does not exist. Is there a setting that I need to check in the Cognito console? My code looks almost identical to the above. I am able to sign-up a user and it works but the sign-in throws the error.

I used this as the basis for the code I wrote: https://aws.amazon.com/blogs/mobile/use-csharp-to-register-and-authenticate-with-amazon-cognito-user-pools/

Error message: {"User pool client XXXX does not exist."}

I can see the ClientId it in the Cognito Console yet the code says it cannot be found even though I just used it to register a user

![Screenshot 2020-10-13 at 02 25 53](https://user-images.githubusercontent.com/32526148/95801711-86091980-0cfb-11eb-94b6-af2474f8f2b6.png)

Your assistance in this regard is greatly appreciated

**Comment by ihiresolutions** [comment]
> @klaytaybai Hi. I apologize for rebooting this issue after such a long time. Turns out I have a similar issue. I got the ClientId and UserPool Id from the Cognito Console and am hard-coding it to test, yet the error indicates that the user pool client does not exist. Is there a setting that I need to check in the Cognito console? My code looks almost identical to the above. I am able to sign-up a user and it works but the sign-in throws the error.
> 
> I used this as the basis for the code I wrote: https://aws.amazon.com/blogs/mobile/use-csharp-to-register-and-authenticate-with-amazon-cognito-user-pools/
> 
> Error message: {"User pool client XXXX does not exist."}
> 
> I can see the ClientId it in the Cognito Console yet the code says it cannot be found even though I just used it to register a user
> 
> ![Screenshot 2020-10-13 at 02 25 53](https://user-images.githubusercontent.com/32526148/95801711-86091980-0cfb-11eb-94b6-af2474f8f2b6.png)
> 
> Your assistance in this regard is greatly appreciated

Hi @klaytaybai - I ended up using the Extensions Nuget package and code from here: https://github.com/aws-samples/aws-cognito-dot-net-desktop-app/blob/master/CognitoHelper.cs

I now have my code working. I did not need to change much, however the Amazon.Extensions.CognitoAuthentication Version 1.0.4 package seems to work quite nicely

**Comment by ashishdhingra** [comment]
Hi @alex-bello,

Please review the https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/136#issuecomment-707425089 and let me know if it resolves your issue.

Thanks,
Ashish

**Comment by lqsantos** [comment]
Hi @ashishdhingra I had the same issue with Version 3.5.0.26. 
After downgraded to version 1.0.4  it works perfectly

**Comment by ashishdhingra** [comment]
Hi @alex-bello,

Please review the https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/136#issuecomment-707425089 and let me know if it resolves your issue.

Thanks,
Ashish

**Comment by faizanktk** [comment]
Fatal error: Uncaught exception 'Aws\CognitoIdentityProvider\Exception\CognitoIdentityProviderException' with message 'Error executing "AdminInitiateAuth" on "https://cognito-idp.us-west-2.amazonaws.com"; AWS HTTP error: Client error: `POST https://cognito-idp.us-west-2.amazonaws.com` resulted in a `400 Bad Request` response: {"__type":"ResourceNotFoundException","message":"User pool client {ID} does not exist."}

**Comment by ntalamdotcom** [comment]
2022.
I have the same error
