### ISSUE TITLE
User Registration Operation Cancelled Exception

### ISSUE THREAD

**Issue by UrizielTSD** [aws/aws-aspnet-cognito-identity-provider#138]
Hello, I´m trying to implement the Cognito example in my Visual Studio 2019 asp.net core 3.0 project, whenever I call Registration the Exception described in #41 occurs.

I tried all the proposed fixes but I can´t make it work.
1) All Nuget Packages are up-to-date

2) Code always jumps out at:
var result = await _userManager.CreateAsync(user, Input.Password);

3) My AWS dev account has admin permission and is visible inside the VS toolkit, I also added the AmazonCognitoPowerUser permission, no changes.

4)I set up the appsettings.dev.json and appsettings.json:

  "AWS": {
    "Region": "eu-west-1",
    "UserPoolClientId": "1t0******",
    "UserPoolClientSecret": "125fo****************",
    "UserPoolId": "eu-west-1_*******"
  },

Any idea would be very much appreciated!

**Comment by UrizielTSD** [comment]
The Projects run inside Beanstalk without a problem, so it seems to be a permission problem on my pc ?

**Comment by klaytaybai** [comment]
My guess is that you don't have the credentials set up properly on your local machine.  The last step in the default fallback credentials chain is to check an EC2/ECS instance for credentials.  Please try following the advice in the second half of #41 regarding getting your permissions to work locally.

**Comment by UrizielTSD** [comment]
Thanks for the reply, my credentials were set correctly.
I added them to the SDK using the provided link, but that didnt help.

But I did find my problem, not sure if that is expected behavior.
My Asp.net core app is dockerized, and when executing it using docker (I use a Linux docker on windows), I presume that AWS credentials arent known to docker.
Running it on IIS Express from studio instead of Docker it works.

Planned is to deploy the app as a docker image to run it on beanstalk later, do docker container get access to the EC2 metadata? Or will the same thing happen like on my local machine ?

**Comment by jlwhitfill** [comment]
You will have this issue always.  You are correct that Docker is causing it because it doesn't know your localized credentials you have configured in your AWS Toolkit for Visual Studio.  Once deployed, it works fine.  Thats why I always run it in regular mode (not in docker mode) when I am debugging.

You second, I would need to see more of what you are doing to see the real  issue but try this where you are having issues:

User?.FindFirst("<your claim name").Value

**Comment by ashishdhingra** [comment]
Hi @UrizielTSD,

Good morning.

I was going thorough a bunch of backlog issues and came across this one. Please let me know if input from @jlwhitfill works and if this issue could be closed.

Thanks,
Ashish
