### ISSUE TITLE
UriFormatException: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by kentbarber** [aws/aws-aspnet-cognito-identity-provider#139]
I am not able to run this project. I have tried in VS 2017 and 2019. Could be a user error since I am just trying to run the Samples.sln directly. These are the errors...

`
UriFormatException: Invalid URI: The hostname could not be parsed.

System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)
System.Uri..ctor(string uriString)
Amazon.Runtime.ClientConfig.GetUrl(RegionEndpoint regionEndpoint, string regionEndpointServiceName, bool useHttp, bool useDualStack) in ClientConfig.cs
Amazon.Runtime.ClientConfig.DetermineServiceURL() in ClientConfig.cs
Amazon.Runtime.Internal.DefaultRetryPolicy..ctor(IClientConfig config) in DefaultRetryPolicy.cs
Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline() in AmazonServiceClient.cs
`

**Comment by klaytaybai** [comment]
I was able to reproduce this.  It would be nice to get the sample solution working

**Comment by ehs035** [comment]
Make sure you add your AWS settings to: appsettings.Development.json

**Comment by ashishdhingra** [comment]
Hi @kentbarber,

Good afternoon.

Based on input by @ehs035, I was able to get the Samples solution working by providing the 
following AWS settings in `appsettings.Development.json`:

```JSON
  "AWS": {
    "Region": "<your region id goes here>",
    "UserPoolClientId": "<your user pool client id goes here>",
    "UserPoolClientSecret": "<your user pool client secret goes here>",
    "UserPoolId": "<your user pool id goes here>"
  }
```

Please confirm if it is working for you and if this issue could be closed.

Thanks,
Ashish
