### ISSUE TITLE
Can a RefreshSigninAsync method be used in a regular .Net Framework MVC application

### ISSUE THREAD

**Issue by mikebama** [aws/aws-aspnet-cognito-identity-provider#141]
Can the RefreshSigninAsync method be used in a regular .Net Framework MVC application that calls API's from a separate project?  I saw your comments on a similar issue for a .NET Core application in this thread: [(Implement the RefreshSigninAsync method #90)](https://github.com/aws/aws-aspnet-cognito-identity-provider/pull/90)

**Comment by klaytaybai** [comment]
It should be. This library and its dependencies target .NET Standard 2.0, so .NET Framework should work but you need to be using a version of .NET Framework that is compatible with .NET Standard 2.0 (4.6.1 or higher).

Have you tried it out?  If you have issues, please reopen this issue or create a new one.
