### ISSUE TITLE
Cognito User Pool Authentication

### ISSUE THREAD

**Issue by mikebama** [aws/aws-aspnet-cognito-identity-provider#145]
AWS team,
I was wondering after a user has been authenticated against a user pool does every request that is submitted by the site get the request authenticated by cognito using the JWT Access Token in the sample project and in general?

Also if multi factor authentication is implemented in the us-east-2 region can SMS messages or just emails be used to multi factor authenticate not including phone or TOTP multi-factor authentication?

Regards,
Mike

**Comment by klaytaybai** [comment]
After being authenticated, the user's temporary access tokens can be used to authenticate to your backend AWS services.  Furthermore, when using this library, you can use Cognito as a user [Identity Provider for ASP.NET](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio) Core.

SMS can be used for multi-factor authentication.

Please refer to these docs for more details:
https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/README.md
https://aws.amazon.com/cognito/faqs/
https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

**Comment by mikebama** [comment]
You mentioned that SMS can be used for multi-factor authentication.   I saw in this link (https://docs.amazonaws.cn/en_us/cognito/latest/developerguide/user-pool-settings-mfa.html) it mentioned "4. Your users can use SMS text message or Time-based One-time Password as a second factor".   Will the otp manager (https://www.microsoft.com/en-us/p/otp-manager/9nblggh6hngn?activetab=pivot:overviewtab ) app on a PC work with cognito for multi factor auth or will just google authenticator work on a smart phone?  How would a non google authenticator TOTP app be setup for Cognito to authenticate?  

Also in the authentication process when using a AWS application load balancer (ALB) as shown in this AWS documentation (https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/ ).  What are the steps exactly that need to be selected in the ALB so users would be forced to authenticate against cognito.  I found this link on authenticating requests, could the cup tokens be added here(https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html ) and (https://docs.aws.amazon.com/general/latest/gr/sigv4-add-signature-to-request.html ).  Could a user be redirected to a login form on an aws hosted web site if a user failed cognito authention on a request to the ALB?  I am on a MVC 5 web site if the users cup token could be   programmatically added to an authorization header to submit it to the ALB for Cognito authentication for all requests not just login requests?  If so please send me some links on how this is accomplished in a web application?  

Thanks,
Mike

**Comment by ashishdhingra** [comment]
Hi @mikebama,

Good morning.

The TOTP functionality appears to be missing from CognitoSignInManager class and there is already a feature request #168 (There was another issue #48 reported earlier and it was advised at time that it would be implemented in later version). Here is what I see in the code for CognitoSignInManager class:

- [CheckPasswordSignInAsync](https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/e54f03d7854e17b05434ed34a3c67fa992ffe45c/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L265) only has a check for ChallengeNameType.SMS_MFA

- [RespondToTwoFactorChallengeAsync](https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/e54f03d7854e17b05434ed34a3c67fa992ffe45c/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L343) appears to have logic for responding to 2-factor MFA.

Also the following articles could help. These articles directly use [AmazonCognitoIDentityProviderClient](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CognitoIdentityProvider/TCognitoIdentityProviderClient.html).

- [Amazon Cognito Credentials Provider](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-creds-provider.html)

- [Amazon CognitoAuthentication Extension Library Examples](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-authentication-extension.html). There is a section called Authenticate with Challenges which specifies use of new password required and MFA scenarios.

Also refer [Simplify Login with Application Load Balancer Built-in Authentication](https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/) on example for using ALB with Cognito.

Please see is it helps and confirm if this issue could be closed.

Thanks,
Ashish

**Comment by mikebama** [comment]
Good Afternoon Ashish,Thanks for the updates.  


Sent from Yahoo Mail for iPhone


On Wednesday, September 2, 2020, 2:09 PM, Ashish Dhingra <notifications@github.com> wrote:




Hi @mikebama,

Good morning.

The TOTP functionality appears to be missing from CognitoSignInManager class and there is already a feature request #168 (There was another issue #48 reported earlier and it was advised at time that it would be implemented in later version). Here is what I see in the code for CognitoSignInManager class:
   
   -    
CheckPasswordSignInAsync only has a check for ChallengeNameType.SMS_MFA

   -    
RespondToTwoFactorChallengeAsync appears to have logic for responding to 2-factor MFA.


Also the following articles could help. These articles directly use AmazonCognitoIDentityProviderClient.
   
   -    
Amazon Cognito Credentials Provider

   -    
Amazon CognitoAuthentication Extension Library Examples. There is a section called Authenticate with Challenges which specifies use of new password required and MFA scenarios.


Also refer Simplify Login with Application Load Balancer Built-in Authentication on example for using ALB with Cognito.

Please see is it helps and confirm if this issue could be closed.

Thanks,
Ashish

**Comment by ashishdhingra** [comment]
@mikebama If above guidance works for you, please confirm if this issue could be closed.
