### ISSUE TITLE
Unable to resolve service for type 'Amazon.AspNetCore.Identity.Cognito.CognitoSignInManager`1[Amazon.Extensions.CognitoAuthentication.CognitoUser]' while attempting to activate 'WebAdvert.Web.Controllers.AccountsController'.

### ISSUE THREAD

**Issue by Erayus** [aws/aws-aspnet-cognito-identity-provider#146]
Hi,

In the README.md, it says to inject CognitoSigninManager, however, I believe it should be CognitoSignInManager (capital I) as that's how it's written in the source code. 

However, although there is no error in the editor, it shows this error after running it: 

`InvalidOperationException: Unable to resolve service for type 'Amazon.AspNetCore.Identity.Cognito.CognitoSignInManager`1[Amazon.Extensions.CognitoAuthentication.CognitoUser]' while attempting to activate 'WebAdvert.Web.Controllers.AccountsController'.
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
lambda_method(Closure , IServiceProvider , object[] )
Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider+<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider+<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

Anyone else run into this issue?

**Comment by Erayus** [comment]
Seems like we can't inject it directly in the constructor. 

To use the class, I have to cast it from SignInManager instead.

await ((CognitoUserManager<CognitoUser>) _userManager).CreateAsync(user, model.Password, validationData);

**Comment by Earpengai** [comment]
To resolve this issue, you can register CognitoUserManager so it can be injected to the DI.

code: 
builder.Services.AddScoped<CognitoUserManager<CognitoUser>>();
