### ISSUE TITLE
AWS Cognito Admin GetUser with associated groups

### ISSUE THREAD

**Issue by junaid-ahmed92** [aws/aws-aspnet-cognito-identity-provider#148]
I am using aws cognito sdk with .net core 3.1 webapi. The issue is, I have to display users info as well as user groups. ListUserApi https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsers.html doesn't return users group information. According to the docs I have to call other api ListUserInGroups (https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListUsersInGroup.html) but as I need both information on single table. This call would be really expensive for me. Is there any other api which returns user's profile info as well as user group info. I tried to find one but couldn't Also one other question do aws cognito api provied sorting functionality? Like sort by name of email? I can only see filtering option but not sorting.

**Comment by klaytaybai** [comment]
Hi @junaid-ahmed92, unfortunately I'm not aware of a call that can get information for both user info and their groups.  It sounds like you would have to do AdminGetUser/ListUsers + AdminListGroupsForUsers.  I'm also not aware of any way to sort on the server-side that doesn't involve filtering on the sort criteria.  I suggest you post in the [Cognito AWS Forums](https://forums.aws.amazon.com/forum.jspa?forumID=173) to discuss your needs more.  You should also direct guidance issues that are not SDK specific to the Forums whenever you can.
