### ISSUE TITLE
Refresh Token using Identity Provider

### ISSUE THREAD

**Issue by WajahatAliAbid** [aws/aws-aspnet-cognito-identity-provider#150]
Hello, I am using cognito identity provider to login my user. For refresh token, I am using the following code snippet.
```csharp
[HttpPost("[action]")]
public async Task<ActionResult<TokenResult>> RefreshToken([FromBody]RefreshTokenRequest refreshTokenRequest)
{
    var authResponse = await cognitoIdentityProvider.AdminInitiateAuthAsync(new AdminInitiateAuthRequest
    {
        AuthFlow = AuthFlowType.REFRESH_TOKEN,
        ClientId = configuration["AWS:UserPoolClientId"],
        UserPoolId = configuration["AWS:UserPoolId"],

        AuthParameters = new Dictionary<string, string>
        {
            {"REFRESH_TOKEN",refreshTokenRequest.Token},
            {"SECRET_HASH",configuration["AWS:UserPoolClientSecret"]}
        }
    });
    return new TokenResult
    {
        IdToken = authResponse.AuthenticationResult.IdToken,
        AccessToken = authResponse.AuthenticationResult.AccessToken,
        Expiry = DateTime.Now.AddSeconds(authResponse.AuthenticationResult.ExpiresIn),
        RefreshToken = authResponse.AuthenticationResult.RefreshToken
    };
}
```
I am not using any authorize attribute for it since I am just passing it refresh token to get me a new id and access token. Is it possible to achieve this functionality using aws-aspnet-cognito-identity-provider? If yes, please guide me on this.

**Comment by klaytaybai** [comment]
Maybe this will help for more context:  https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/76

**Comment by WajahatAliAbid** [comment]
I tried this issue, although I do not have `CognitoUser` at the point of when I am refreshing the token. Just a refresh token. So I cannot use any method that requires instance of `CognitoUser`, for example `CognitoUser.StartWithRefreshTokenAuthAsync()` or `CognitoSigninManager.RefreshSignInAsync(CognitoUser).`

**Comment by ashishdhingra** [comment]
Hi @WajahatAliAbid,

Following code within the SDK could be helpful:

1.  Refer [Authenticating using a Refresh Token from a Previous Session](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/53b8d465698ed6b1f0e810fb9fb59a1d4d35a4db/README.md#authenticating-using-a-refresh-token-from-a-previous-session) in in [aws-sdk-net-extensions-cognito](https://github.com/aws/aws-sdk-net-extensions-cognito) repository. This uses [CognitoUser.StartWithRefreshTokenAuthAsync](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/832be0a6792b1c988c08f0767de7ee845235deae/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L243).

2. [CognitoSignInManager. RefreshSignInAsync()](https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/e54f03d7854e17b05434ed34a3c67fa992ffe45c/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L209) in [aws-aspnet-cognito-identity-provider](https://github.com/aws/aws-aspnet-cognito-identity-provider) repository.

Refresh/session tokens are associated with a user, hence you would need to have user in place as required by these calls.

Please let me know if this provides the required guidance and we could close this issue.

Thanks,
Ashish

**Comment by duaneking** [comment]
This needs to be reopened; finding data on this is difficult and the often misleading docs and lack of examples don't make it easier.
