### ISSUE TITLE
Mock testing CognitoUser instance

### ISSUE THREAD

**Issue by WajahatAliAbid** [aws/aws-aspnet-cognito-identity-provider#151]
Is there a way to mock test `CognitoUser` instance using [moq](https://github.com/moq/moq4), from my understanding the method `StartWithAdminNoSrpAuthAsync` isn't virtual so it cannot be mocked. How can we mock this functionality?

```csharp
var cognitoUser = new Mock<CognitoUser>(It.IsAny<string>(), It.IsAny<string>(), userPool.Object, Mock.Of<IAmazonCognitoIdentityProvider>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<string>(), It.IsAny<Dictionary<string, string>>());
cognitoUser.Setup(x=> x.StartWithAdminNoSrpAuthAsync(Mock.Of<InitiateAdminNoSrpAuthRequest>())).ReturnsAsync(It.IsAny<AuthFlowResponse>());
```
Error screenshot
![image](https://user-images.githubusercontent.com/17341777/76680269-f6867580-6608-11ea-91d9-8a87b5089949.png)

**Comment by klaytaybai** [comment]
Hi @WajahatAliAbid, thanks for the feedback.  I agree that it would be nice if this was supported more simply.  You should be able to mock it if you write a subclass to wrap around the CognitoUser class.  You can then just return the invocations of the base methods and mock on the new class and its methods.

```
        public virtual new Task<AuthFlowResponse> StartWithAdminNoSrpAuthAsync(InitiateAdminNoSrpAuthRequest adminAuthRequest)
        {
            return base.StartWithAdminNoSrpAuthAsync(adminAuthRequest);
        }
 ```

**Comment by WajahatAliAbid** [comment]
Hi @klaytaybai 
I tested it with using a custom subclass of `CognitoUser` 
```csharp
public class CustomCognitoUser : CognitoUser
    {
        public CustomCognitoUser(string userID, string clientID, CognitoUserPool pool, IAmazonCognitoIdentityProvider provider, string? clientSecret = null, string? status = null, string? username = null, Dictionary<string, string>? attributes = null) : base(userID, clientID, pool, provider, clientSecret, status, username, attributes)
        {
        }
        public virtual new Task<AuthFlowResponse> StartWithAdminNoSrpAuthAsync(InitiateAdminNoSrpAuthRequest adminAuthRequest)
        {
            return base.StartWithAdminNoSrpAuthAsync(adminAuthRequest);
        }
    }
```
This issue has been resolved. Thanks for your feedback. I'm looking forward to future releases of `aws-aspnet-cognito-identity-provider` with support for mocking without writing a wrapper class for it.

**Comment by WajahatAliAbid** [comment]
@klaytaybai can you look at [this](https://github.com/aws/aws-sdk-net-extensions-cognito/pull/49) PR please?
