### ISSUE TITLE
Don't know how to authenticate with SAML IdP authentication flow

### ISSUE THREAD

**Issue by danielmedina** [aws/aws-aspnet-cognito-identity-provider#152]
Hey there.

I'm working with a SAML IdP authentication flow. It means that I use a cognito url to redirect me to my Identity Provider where I sign in (two factor authentication included) and then redirected to my application with an authorization code (my callback address with ?code=<authorization code>. 

I tested this flow using postman and everything runs very well.

Using this library (aws aspnet identity provider), how should I proceed once I have an authorization code?

I'm trying to do this: 

```
var cognitoSignInManager = (SignInManager as CognitoSignInManager<CognitoUser>);
//tryed this with no success
//var user1 = await cognitoSignInManager.GetTwoFactorAuthenticationUserAsync();

//I thought it was the answer, but it returns failed
var result = await cognitoSignInManager.RespondToTwoFactorChallengeAsync(code, false, false);

return Ok(result);
```

The setup in ConfigureServices (Startup.cs):

```
var cognitoIdentityProvider = new AmazonCognitoIdentityProviderClient();
services.AddSingleton<IAmazonCognitoIdentityProvider>(cognitoIdentityProvider);
services.AddSingleton<CognitoUserPool>(new CognitoUserPool("fasdfasdfasdf", 
                                                           "asdfasdfasdfasd", 
                                                           cognitoIdentityProvider, 
                                                           "ghhjfgjfghjfghj"));

services.AddCognitoIdentity();

```
In Configure (Startup.cs)

`app.UseAuthentication();`

**Update 1**
I downloaded the source and referenced in my solution and main project. I don't know why, but this CognitoSinginManager method isn't return a suceed result... I don't know why and where to fix it...

```
private async Task<TwoFactorAuthenticationInfo> RetrieveTwoFactorInfoAsync()
        {
            var result = await Context.AuthenticateAsync(IdentityConstants.TwoFactorUserIdScheme).ConfigureAwait(false);
            if (result?.Principal != null){
              ...
              ...
              ...
            }
```

It's executed by `public async Task<SignInResult> RespondToTwoFactorChallengeAsync(string code, bool isPersistent, bool rememberClient)` that's the method I'm trying to use...

**Comment by glindstr** [comment]
I'm just wondering if you found a solution to this. I'm also trying to figure out how to get this library to log in a user from an authentication code from a third party provider.
