### ISSUE TITLE
Authenticate Users Using an Application Load Balancer

### ISSUE THREAD

**Issue by mikebama** [aws/aws-aspnet-cognito-identity-provider#153]
AWS Staff,
      I am inquiring to find out more about the "[Authentication Flow" process when "Authenticate Users Using an Application Load Balancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-authenticate-users.html)".  When the "Authenticate Users Using an Application Load Balancer" is configured using Cognito as discussed in the "Configure User Authentication" section in the enclosed link can the Load Balancer be configured to redirect an application user to a login page in the .Net web application?  Also are all web requests after signing into Cognito using the SDK protected to insure that the user has a valid authenticated session using the session cookie to maintain authentication status?

Thanks,
Mike

**Comment by ashishdhingra** [comment]
Hi @mikebama,

Good morning.

I was going through the issue backlog and came across this guidance question. 

While there is a way to use custom login page in an ASP.NET web application with Cognito (please check the [Sample solution](https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/samples) in [aws-aspnet-cognito-identity-provider](https://github.com/aws/aws-aspnet-cognito-identity-provider/) repository), I don’t think there is a way to redirect to custom login page when using Elastic Load Balancer authentication with Cognito. This integration process occurs outside the application and Amazon Cognito works seamlessly with ELB authentication. We can customize the Cognito hosted UI (refer the documentation link [Using the Amazon Cognito Hosted UI for Sign-Up and Sign-In](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-integration.html)) though. 

Please let me know if this provides enough guidance and if this issue could be closed.

Thanks,
Ashish
