### ISSUE TITLE
Exception registering user

### ISSUE THREAD

**Issue by Galluz75** [aws/aws-aspnet-cognito-identity-provider#155]
I've tried to use the sample project to make a simple user registration test, but the method `_userManager.CreateAsync` generate an exception, I've tried in different ways getting different exception:

1) I've use the standard configuration using appsetting.json to store Cognito parameters, I didn't modify anything else in the project.
Result: 
```
SocketException: No route to host
HttpRequestException: No route to host
```

2) Suspecting a problem getting configuration from json I've used a different configuration, working on Startup - ConfigureServices:

```c#
services.AddSingleton<IAmazonCognitoIdentityProvider>(p =>
{
    return new AmazonCognitoIdentityProviderClient(new Amazon.Runtime.AnonymousAWSCredentials(), Amazon.RegionEndpoint.USEast1);
});

services.AddSingleton<CognitoUserPool>(p =>
{
    var provider = p.GetService<IAmazonCognitoIdentityProvider>();
    return new CognitoUserPool(“xxxxxxxx”, “yyyyyyyyyyyyyyyy”, provider);
});

services.AddCognitoIdentity();
```

Result: 
```
HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown
AmazonCognitoIdentityProviderException: Missing Authentication Token
```

3) I've tried to replace Client App Id with another (without secret) successfully tested using a simple console application
Result: same errors of point 2

I was not expecting so many problems for this simple test, any suggestion?

**Comment by ashishdhingra** [comment]
Hi @Galluz75,

Good evening.

I tried using the [sample project](https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/samples) in [aws-aspnet-cognito-identity-provider](https://github.com/aws/aws-aspnet-cognito-identity-provider) repository along with option 2 above while debugging locally using Visual Studio 2019 and was successfully able to create user using the Register option on the top right on Home page.

<img width="849" alt="Untitled" src="https://user-images.githubusercontent.com/67916761/92664305-75a6ee80-f2b8-11ea-994f-96253d7ad2ac.png">


The Register post action has the following logic:

```C#
public async Task<IActionResult> OnPostAsync(string returnUrl = null)
{
    returnUrl = returnUrl ?? Url.Content("~/");
    if (ModelState.IsValid)
    {
        var user = _pool.GetUser(Input.UserName);
        user.Attributes.Add(CognitoAttribute.Email.AttributeName, Input.Email);

        var result = await _userManager.CreateAsync(user, Input.Password);
        if (result.Succeeded)
        {
            _logger.LogInformation("User created a new account with password.");

            await _signInManager.SignInAsync(user, isPersistent: false);

            return RedirectToPage("./ConfirmAccount");
        }
        foreach (var error in result.Errors)
        {
            ModelState.AddModelError(string.Empty, error.Description);
        }
    }

    // If we got this far, something failed, redisplay form
    return Page();
}
```

Please ensure that app pool has proper settings to allow API access and `app settings.Development.json` (for debugging), has the following settings:
```JSON
"AWS": {
    "Region": "<your region id goes here>",
    "UserPoolClientId": "<your user pool client id goes here>",
    "UserPoolClientSecret": "<your user pool client secret goes here>",
    "UserPoolId": "us-east-1_JUtIuj13A"
  }
```

Please let me know if it helps.

Thanks,
Ashish

**Comment by Galluz75** [comment]
Hello Ashish,
thank you very much for the support, at the moment I am busy on other activity but I will test again using your suggestion as soon as possible, I will let you know the result.
Kind regards
Fabio
