### ISSUE TITLE
Trying to Integrate with MVC ASP.NET Core 3.1

### ISSUE THREAD

**Issue by Brett-Riverboat** [aws/aws-aspnet-cognito-identity-provider#160]
Hello

I am fairly new to MVC ASP.NET Core 3.1 want to integrate the identity pages with a typical MVC web app.

I copied login.cshtml (and its model) to Views/Identity on a new app. I copied _LoginPartial to Shared and referenced it from _Layout.cshtml as in the sample application. I also changed _LoginPartial to reference my identity contoller instead of the old way.

When I click on the login link I get a null reference exception at:
"if ((Model.ExternalLogins?.Count ?? 0) == 0)"

For Model. I do not understand what is supposed to be instantiating the model here. 

(I cannot run the samples application as it was downloaded else I get an exception like:
"UriFormatException: Invalid URI: The hostname could not be parsed.")

**Comment by ashishdhingra** [comment]
Hi @Brett-Riverboat,

Good afternoon.

Following resources from Microsoft's website provide good reference for migrating existing ASP.NET MVC application to .NET Core MVC application:

1. [Migrate from ASP.NET MVC to ASP.NET Core MVC](https://docs.microsoft.com/en-us/aspnet/core/migration/mvc?view=aspnetcore-3.1)

2. [Migrate Authentication and Identity to ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/migration/identity?view=aspnetcore-3.1)

Please let me know if it helps.

Thanks,
Ashish
