### ISSUE TITLE
PasswordSignInAsync behavior when MFA_SETUP challenge occured

### ISSUE THREAD

**Issue by idanalt** [aws/aws-aspnet-cognito-identity-provider#162]
Hi,
I'm using this SDK for building a custom login page with Cognito,
when user sign in for the first time and MFA is enabled, he need to setup MFA device first
but PasswordSignInAsync not telling me that MFA Setup is required, i'm receiving failed to login
there is a support for mfa setup? and if not how can I deal with that?

Thanks

**Comment by ashishdhingra** [comment]
Hi @idanalt,

Thanks for reporting the guidance question. I looked at the code and as per line logic in [CognitoSigninManager](https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/6f8d985deef49bcce485d27cd52acf8ab9d45aaa/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L265), you may try checking the return value of _PasswordSignInAsync()_ call for the value SignInResult.TwoFactorRequired. Please reply back if it  handles the your check MFA.

Thanks,
Ashish
