### ISSUE TITLE
AdminSetUserPassword is not supported in IAmazonCognitoIdentityProvider (.Net Core 3.1)

### ISSUE THREAD

**Issue by momalley** [aws/aws-aspnet-cognito-identity-provider#165]
## Description
AdminSetUserPassword is not supported.

## Reproduction Steps
The AdminSetUserPassword method does not exist on IAmazonCognitoIdentityProvider.

### Logs
N/A

### Environment
Amazon.AspNetCore.Identity.Cognito v1.0.5
Amazo.Extensions.CognitoAuthentication v1.0.4
.NETCoreApp 3.0
Visual Studio 2019
Windows 10
Targeting .NET Core 3.1

## Resolution

Please add support for this call.

---

This is a :bug: bug-report

**Comment by normj** [comment]
For .NET Core the service interfaces like IAmazonCognitoIdentityProvider only support the async versions of the operation. So you should see AdminSetUserPasswordAsync.

This is due to the HttpClient in .NET Core only supporting async requests.
