### ISSUE TITLE
Qustion: An error was encountered with the requested page

### ISSUE THREAD

**Issue by kawabata2018** [aws/aws-aspnet-cognito-identity-provider#167]
### Situation
I followed this article to connect to the Cognito sign-in page using Hosted UI.
https://chandradev819.wordpress.com/2020/01/18/aws-cognito-service-in-asp-net-core-3-1-application/

I have tried several times. (the callback url is set as https://localhost:5001)
But it only redirects to the error page like below.
URL: `https://__MYDOMAIN_.auth.us-east-2.amazoncognito.com/error?error=redirect_mismatch&client_id=__MYCLIENTID__`
<img src="https://user-images.githubusercontent.com/42432622/89156360-88d1ea80-d5a5-11ea-9ce6-3da3da833a50.png">

I'm not familiar with both ASP.NET Core and Cognito ...
What does this error message mean?
What should I do to solve this problem?

### Environments
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1
```

**Comment by ashishdhingra** [comment]
Hi @kawabata2018, 

Thanks for posting the guidance question. Following resources could be helpful to get started with Amazon Cognito:

1. Video [Using AWS Cognito in your .NET Core App](https://www.youtube.com/watch?v=LcD_-p1gCww) from AWS team provides good overview.

2. The guidance article [Access AWS services from an ASP.NET Core app using Amazon Cognito identity pools](https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/access-aws-services-from-an-asp-net-core-app-using-amazon-cognito-identity-pools.html) provides step-by-step exercise. It also has link to [Sample .NET Core web app](https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/samples) in AWS Cognito GitHub repository.

Please let me know if this provides necessary support.

Thanks,
Ashish

**Comment by kawabata2018** [comment]
Thank you so much @ashishdhingra,

I have cloned the [sample application](https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/samples) and tried to fix it so that it will run on my environment -- ASP.NET Core 3.1.
I'm currently working on an MVC app on the localhost and would like to add the Cognito authentication feature for this.
Is it quite difficult to implement for beginners like me?
Could you give me some advice about that?

Best regards,

**Comment by ashishdhingra** [comment]
Hi @kawabata2018, 

Implementing Cognito authentication feature should not be difficult to implement. [AWS Cognito documentation](https://docs.aws.amazon.com/cognito/?id=docs_gateway) is the best resource for reference to learn more about this component. For ASP.NET Core, there is plenty of information available on [Microsoft's ASP.NET website](https://dotnet.microsoft.com/apps/aspnet/web-apps).

Please let me know if we are good to close this guidance issue.

Thanks,
Ashish
