### ISSUE TITLE
AWS Cognito Multi-factor authentication using TOTP always returns failed in C# .net core

### ISSUE THREAD

**Issue by tavisca-anjoshi** [aws/aws-aspnet-cognito-identity-provider#168]
## Description
We want to achieve login functionality in our application using our own custom UI instead of hosted UI provided by Cognito. We have a requirement of MFA using TOTP(software token) for login purposes. For that, we have enabled the second factor using a Time-based One-time Password for the user pool.

## Reproduction Steps
1. We referred to the following sample code provided by AWS https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/samples/Samples/Areas/Identity/Pages/Account.
2. In this sample, MFA is done using an SMS token. But we want to use TOTP using the authenticator app instead. As application users are not providing their mobile number.
3. We were able to log in without MFA enabled, but when we enabled MFA (software token) via c# code for cognito user, then login functionality doesn't work in our custom UI but its working in Cognitohosted UI.
4. While using _signInManager.PasswordSignInAsync returns failed despite the username and password being correct.
5. Please refer to the application code.

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");

            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false);
                if (result.Succeeded)
                {
                    await CryptoLogger.LogTraceAsync(Constants.Logging.TraceCategory.Login, "User logged in.", new Dictionary<string, object> { { "email", Input.Email.MaskEmail() } });
                    return RedirectToPage("./EnableAuthenticator");
                }
                else if (result.RequiresTwoFactor)
                {
                    return RedirectToPage("./LoginWith2fa", new { ReturnUrl = returnUrl, RememberMe = Input.RememberMe });
                }
                else if (result.IsCognitoSignInResult())
                {
                    if (result is CognitoSignInResult cognitoResult)
                    {
                        var encodedEmail = WebUtility.UrlEncode(Input.Email);

                        if (cognitoResult.RequiresPasswordChange)
                        {
                            await CryptoLogger.LogTraceAsync(Constants.Logging.TraceCategory.Login, "User password needs to be changed", new Dictionary<string, object> { { "email", Input.Email.MaskEmail() } });
                            return RedirectToPage("./ChangePassword", new { email = encodedEmail });
                        }
                        else if (cognitoResult.RequiresPasswordReset)
                        {
                            await CryptoLogger.LogTraceAsync(Constants.Logging.TraceCategory.Login, "User password needs to be reset", new Dictionary<string, object> { { "email", Input.Email.MaskEmail() } });
                            return RedirectToPage("./ResetPassword", new { email = encodedEmail });
                        }
                    }
                }

                ModelState.AddModelError(string.Empty, "Invalid login attempt.");
                return Page();
            }

            return Page();
        }

When the user is logged in we are forcefully setting up a TOTP for a particular user. Once done with the TOTP setup we are not able to log in again. Though all settings of UserPool are correct. Please see below code
  
        //Enabling authenticator for particular user
        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                throw new InvalidOperationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            if (!ModelState.IsValid)
            {
                await GetSharedKeyAndQrCodeUriAsync(user, Input);
                return Page();
            }

            var verificationCode = Input.Code.Replace(" ", string.Empty).Replace("-", string.Empty);

            var cognito = new AmazonCognitoIdentityProviderClient(RegionEndpoint.USEast1);
            var verifySoftwareTokenRequest = new VerifySoftwareTokenRequest()
            {
                AccessToken = user.SessionTokens.AccessToken,
                UserCode = verificationCode
            };
            var verifySoftwareTokenResponse = await cognito.VerifySoftwareTokenAsync(verifySoftwareTokenRequest);

            if (verifySoftwareTokenResponse.Status == "ERROR")
            {
                ModelState.AddModelError("Code", "Verification code is invalid.");
                await GetSharedKeyAndQrCodeUriAsync(user, Input);
                return Page();
            }

            var setUserMFAPreferenceRequest = new SetUserMFAPreferenceRequest()
            {
                AccessToken = user.SessionTokens.AccessToken,
                SoftwareTokenMfaSettings = new SoftwareTokenMfaSettingsType()
                {
                    Enabled = true,
                    PreferredMfa = true
                }
            };
            await cognito.SetUserMFAPreferenceAsync(setUserMFAPreferenceRequest);
            await CryptoLogger.LogTraceAsync(Constants.Logging.TraceCategory.Login, "User has enabled 2FA with an authenticator app.", new Dictionary<string, object> { { "email", user.Username.MaskEmail() } });

            return Page();
        }

---

This is a :bug: bug-report

**Comment by tavisca-anjoshi** [comment]
Hi @ashishdhingra,

I found out that TOTP functionality is missing in Amazon.Extensions.CognitoAuthentication Version=1.0.4.
As I can see PR created for https://github.com/aws/aws-sdk-net-extensions-cognito/issues/55
PR:- https://github.com/aws/aws-sdk-net-extensions-cognito/pull/56.

After getting merge above PR to master, still, it will not solve the issue.

As we need to solve (https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/48)issue present in opened in Amazon.AspNetCore.Identity.Cognito SDK. So we need to change there as well. 

We are waiting for it. Request you to please check.

Thanks,
Aniket

**Comment by ashishdhingra** [comment]
Hi @tavisca-anjoshi,

Good morning.

I think you are correct. The TOTP functionality is missing, there was another issue #48 reported earlier and it was advised at time that it would be implemented in later version. I would treat this as a feature request and discuss with the development team to add this to their backlog. I'm not sure how sooner it would be implemented, but would definitely bring it to team's attention. 

Thanks,
Ashish

**Comment by tavisca-anjoshi** [comment]
Alright. Thanks for the help.

**Comment by ashishdhingra** [comment]
PR https://github.com/aws/aws-aspnet-cognito-identity-provider/pull/173 merged.
