### ISSUE TITLE
Can I Sign in with App1 and keep authorize state to use in the App2 in the same domain?

### ISSUE THREAD

**Issue by GodSpeedXI** [aws/aws-aspnet-cognito-identity-provider#169]
## Can I Sign in with App1 and keep authorize state to use in the App2 in the same domain?

I want to to create App1 as the login and signup. and App2 as a service web app. 
These app are deploy in the same cluster and domain.
So, how to make App2 can keep user identity from the App1?

### Environment

* Build Version: 1.0.5
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  Net Core 3.1

---

**Comment by ashishdhingra** [comment]
Hi @GodSpeedXI, 

Thanks for posting guidance question.

You scenario appears to be a good candidate for single sign-on workflow. It is specific to ASP.NET and should not be dependent on ASP.NET Cognito Identity provider. The article should provide some guidance  [Share authentication cookies among ASP.NET apps](https://docs.microsoft.com/en-us/aspnet/core/security/cookie-sharing?view=aspnetcore-3.1) which could enable to implement single sign-on. Please let me know if this provides necessary guidance.

Thanks,
Ashish
