### ISSUE TITLE
Login session handling

### ISSUE THREAD

**Issue by GodSpeedXI** [aws/aws-aspnet-cognito-identity-provider#170]
I have created scenario that a user login on the office computer with checking remember when login 
and then forgot to logout after work.  
I want to design a page the user can login from another computer to see the active session and delete
before expired.

I need to know this lib is capable to do this and show me a sample.

Thanks

### Environment

* Build Version: Amazon.AspNetCore.Identity.Cognito 1.0.5
* OS Info:  Ubuntu | Windows10
* Build Environment: Visual Studio
* Targeted .NET Platform:  Net Core 3.1

---

**Comment by ashishdhingra** [comment]
Hi @GodSpeedXI,

Good morning.

Thanks for posting the guidance question. I'm not sure if Amazon Cognito provides this functionality out of the box. Cognito is primarily used as an identity provider for authenticating users. This appears to be a custom scenario. However, you may have a look at the [IAmazonCognitoIdentityProvider.GlobalSignOut (GlobalSignOutRequest)](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CognitoIdentityProvider/MICognitoIdentityProviderGlobalSignOutGlobalSignOutRequest.html) which signs out users from all devices and also invalidates all refresh tokens issued to a user. Service API documentation also specifies details about [GlobalSignOut](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GlobalSignOut.html). 

For handling Global SignOut from the application, there could be some listener from client which validates the current session or listens for this event via WebSocket API. The client after receiving an event could redirect to login page. This is just a thought, not a validated solution. As of now, I cannot find a running sample and you might have to develop some sample application which uses GlobalSignOut functionality.

Please let me know if this helps.

Thanks,
Ashish

**Comment by GodSpeedXI** [comment]
I see in the cognito user pool in each user section there is a list of devices.
![DeviceSection](https://user-images.githubusercontent.com/34591325/92362407-29be4300-f11a-11ea-88ff-6a7a08ff82f3.PNG)

When user sign-in on pc browser , I want cognito to remember the device when the session is active. 
How I could  do this approach?

**Comment by ashishdhingra** [comment]
Hi @GodSpeedXI, 

Please refer the article [Specifying User Pool Device Tracking Settings](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-device-tracking.html) and let me know if it helps.

Thanks,
Ashish
