### ISSUE TITLE
Stuck in forgot password flow

### ISSUE THREAD

**Issue by fredericof** [aws/aws-aspnet-cognito-identity-provider#175]
## Description
Hello, 
I'm currently developing the forgot password flow with Cognito extension for ASP.NET and I'm stuck with the step when I receive the confirmation code on my email.

## Reproduction Steps
Starting by calling ForgotPassword method that sends to my email a confirmation code, but when I set confirmation code at the ConfirmForgotPassword method, it throws ExpiredCodeException. Another weird thing I realized is that Account Status of User does not changes to "Enabled / RESET_REQUIRED".

### Sample Code
ForgotPassword to request to change a user password
```
            try
            {
                ForgotPasswordResponse forgotPasswordResponse = await client.ForgotPasswordAsync(forgotPasswordRequest);
                response = new DTOCognitoForgotPasswordResponse()
                {
                    ConfirmationCodeWasDelivered = true
                };
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
            return response;
        }
```
ConfirmForgotPassword to change the user password with the confirmation code
```
try
            {
                ConfirmForgotPasswordResponse confirmForgotPasswordResponse = await client.ConfirmForgotPasswordAsync(confirmForgotPasswordRequest);
                response = new DTOCognitoConfirmForgotPasswordResponse()
                {
                    PasswordWasChanged = true
                };
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
```

Thanks,
Frederico

**Comment by ashishdhingra** [comment]
Hi @fredericof,

I'm not sure if it helps, the article [User Authentication For Web And iOS Apps With AWS Cognito (Part 2)](https://www.smashingmagazine.com/2017/09/user-authentication-web-ios-apps-aws-cognito-part-2/) gives a good overview of the Forgot Password workflow. Please let me know if it helps.

Thanks,
Ashish

**Comment by iofluxdev1** [comment]
For over a year now I have been bashing my head against the wall trying to resolve the following error:

Failed to change the Cognito User password : Invalid code provided, please request a code again.
