### ISSUE TITLE
Support for AWSSDK.Core 3.5?

### ISSUE THREAD

**Issue by iofluxdev1** [aws/aws-aspnet-cognito-identity-provider#176]
## Description
When referencing any package that has AWSSDK.Core 3.5 as a dependency then we get the following issue:

Detected package version outside of dependency constraint: XXX requires AWSSDK.Core (>= 3.3.103.2 && < 3.4.0) but version AWSSDK.Core 3.5.1.5 was resolved.

## Reproduction Steps
Install any AWS SDK library version that references AWSSDK.Core 3.5+ alongside this one.

### Logs

Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1608	Detected package version outside of dependency constraint: AWSSDK.CognitoIdentity 3.3.100 requires AWSSDK.Core (>= 3.3.100 && < 3.4.0) but version AWSSDK.Core 3.5.1.10 was resolved.	XXX.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: AWSSDK.CognitoIdentityProvider 3.3.100 requires AWSSDK.Core (>= 3.3.100 && < 3.4.0) but version AWSSDK.Core 3.5.1.10 was resolved.	XXX.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: AWSSDK.Extensions.NETCore.Setup 3.3.100.1 requires AWSSDK.Core (>= 3.3.100 && < 3.4.0) but version AWSSDK.Core 3.5.1.10 was resolved.	XXX.csproj	1	
Warning	NU1608	Detected package version outside of dependency constraint: AWSSDK.SecurityToken 3.3.100 requires AWSSDK.Core (>= 3.3.100 && < 3.4.0) but version AWSSDK.Core 3.5.1.10 was resolved.	XXX.csproj	1

### Environment
* Build Version: 1.0.5
* OS Info: Windows 10
* Build Environment: Visual Studio
* Targeted .NET Platform:  .NET Core 3.1

## Resolution
Any ETA on support for AWSSDK.Core 3.5? Thanks!

---

This is a :bug: bug-report

**Comment by Mazekiller** [comment]
I am having the same issue. I find it bad that in over a month nobody from AWS has responded.

**Comment by ashishdhingra** [comment]
This should be fixed in [Amazon.AspNetCore.Identity.Cognito 2.0.2](https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/2.0.2).

**Comment by duaneking** [comment]
Still cant update.
