### ISSUE TITLE
How to override authentication identity expiration?

### ISSUE THREAD

**Issue by MarneeDear** [aws/aws-aspnet-cognito-identity-provider#177]
I would like to set the authentication expiration to 15 minutes instead of the 1 hour default. I have tried using this:

```
    let authProps = new Microsoft.AspNetCore.Authentication.AuthenticationProperties()
    authProps.ExpiresUtc <- new System.Nullable<System.DateTimeOffset>(System.DateTimeOffset.UtcNow.AddMinutes(15.0))                                
    authProps.IsPersistent <- true
    signInManger.SignInAsync(user, authProps)
```

But when a user signs in like that they can't change their email. When I try to send a confirmation token I get this error:

 `[Failed to get the Cognito User attribute verification code : 1 validation error detected: Value at 'accessToken' failed to satisfy constraint: Member must not be null]`

I also am setting CookieAuthenticationOptions in startup like this, but the ExpireTimeSpan doesnt appear to be respected:

```
let authOptions (opts:CookieAuthenticationOptions) =
    opts.Cookie.HttpOnly <- true
    opts.ExpireTimeSpan <- TimeSpan.FromMinutes(30.0)
    opts.LoginPath <- new PathString("/")
    opts.LogoutPath <- new PathString("/signout")
    opts.AccessDeniedPath <- new PathString("/unauthorized")
    opts.SlidingExpiration <- true
    opts.Cookie.SecurePolicy <- CookieSecurePolicy.Always
    opts.Cookie.SameSite <- SameSiteMode.Strict
```

Package versions

```
Amazon.AspNetCore.Identity.Cognito (1.0.5)
      Amazon.Extensions.CognitoAuthentication (>= 1.0.3)
      AWSSDK.CognitoIdentity (>= 3.3.100 < 4.0)
      AWSSDK.CognitoIdentityProvider (>= 3.3.100 < 4.0)
      AWSSDK.Extensions.NETCore.Setup (>= 3.3.100.1 < 4.0)
      Microsoft.AspNetCore.Identity (>= 2.1.6) - restriction: || (&& (== netcoreapp3.1) (< netcoreapp3.0)) (== netstandard2.0)
      Microsoft.Extensions.DependencyInjection (>= 2.1.1) - restriction: || (&& (== netcoreapp3.1) (< netcoreapp3.0)) (== netstandard2.0)
      Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 5.4)
    Amazon.Extensions.CognitoAuthentication (1.0.4)
      AWSSDK.CognitoIdentity (>= 3.3.100 < 4.0)
      AWSSDK.CognitoIdentityProvider (>= 3.3.100 < 4.0)
```

---

This is a :question: general question

**Comment by MarneeDear** [comment]
Related issue
https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/50

**Comment by ashishdhingra** [comment]
Hi @MarneeDear,

I'm not sure if this helps, but as per Microsoft documentation for [SlidingExpiration](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.builder.cookieauthenticationoptions.slidingexpiration?view=aspnetcore-1.1&viewFallbackFrom=aspnetcore-3.1), when it is set to true, it instructs the middleware to re-issue a new cookie with a new expiration time any time it processes a request which is more than halfway through the expiration window. Not sure if this is causing the ExpireTimeSpan not to be respected.

Thanks,
Ashish

**Comment by MarneeDear** [comment]
Thank you.

I do have sliding expiration set to true. I do want it to be true because I only want the auth cookies to invalidate after 15 minutes of idle.

My steps are like this:

1. sign on
2. Wait 20 minutes
3. Auth cookies are considered valid and I am not redirected to the sign on page

I will try with sliding expiration set to false and see what happens
