### ISSUE TITLE
CognitoUserManager sets the ExpirationTime and IssuedTime on the user session as UTC time when IsValid expects Local time

### ISSUE THREAD

**Issue by jbrookssmokeball** [aws/aws-aspnet-cognito-identity-provider#189]
When the `SessionTokens` on the user are created, UTC times for IssuedTime and ExpirationTime are passed into the `CognitoUserSession` constructor:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/76cd6bef8de030c77702e5c9b9441d521c09d789/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L161-L168

However when [CognitoUserSession.IsValid](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/94375b4d1d4262e5c9c99cdf23e63b4ec17fb811/src/Amazon.Extensions.CognitoAuthentication/CognitoUserSession.cs#L74-L79) is called, it compares the `ExpirationTime` against `DateTime.Now`.

```
        public bool IsValid()
        {
            DateTime currentTimeStamp = DateTime.Now;

            return (currentTimeStamp.CompareTo(ExpirationTime) < 0);
        }
```

This means a server which is running on a timezone ahead of UTC may throw an exception saying that the user is not authenticated (when they are) on some calls in `CognitoUser` which rely on `EnsureUserAuthenticated()` (e.g. [UpdateAttributesAsync](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/94375b4d1d4262e5c9c99cdf23e63b4ec17fb811/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L302-L314)) depending on how long the token is valid for.

So I think `CognitoUserSession` should be created using local time for IssuedTime and ExpirationTime and then converted back to UTC time as needed i.e. call `.ToUniversalTime()` when setting ExpiresUtc and IssuedUtc on `AuthenticationProperties`

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/76cd6bef8de030c77702e5c9b9441d521c09d789/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L160-L169

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/76cd6bef8de030c77702e5c9b9441d521c09d789/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L209-L228

**Comment by ashishdhingra** [comment]
Hi @jbrookssmokeball,

Good morning.

I'm not sure if this is an issue since there is another issue logged in Cognito Extensions repository https://github.com/aws/aws-sdk-net-extensions-cognito/issues/21 which mentions the behavior opposite way and it has already been prioritized by development team. Request you to have a look at that issue and re-review your request.

Thanks,
Ashish

**Comment by jbrookssmokeball** [comment]
Hi @ashishdhingra,

Ah yep that seems like the more correct fix. I will close this issue then.

Thanks,
@jbrookssmokeball
