### ISSUE TITLE
Ways of supporting social login

### ISSUE THREAD

**Issue by CheeseNPort** [aws/aws-aspnet-cognito-identity-provider#194]
I am using this package with .Net Core 5 for authentication and we need to support Facebook and Google logins. As I could not find examples on how to use that with this package specifically, we went around it the way we did before. That was to use the OAUth 2 flow. I did that and got back the code, now I have an access token, id token etc. and I was wondering if somehow I can initialate an authorised CognitoUser using this access token.

Please note, I realise I could use Jwt authentication and do away with this library altogether but I do not want to use the OAuth 2 flow for anything other than social logins.

**Comment by ashishdhingra** [comment]
Hi @CheeseNPort,

Good morning.

Following articles might be helpful for integrating Cognito with you application:
- [Authenticating Serverless ASP.NET Core Web APP Using Amazon Cognito](https://www.youtube.com/watch?v=M6qTrI7kmZk) 
- [How to use AWS Cognito with .NET Core](https://developerhandbook.com/aws/how-to-use-aws-cognito-with-net-core/)
- [Integrate Amazon Cognito with .NET Core ASP.NET MVC Application](https://net-immersionday.workshop.aws/9-how-to-authenticate-users-in-my-application.html)

Hope this helps.

Thanks,
Ashish
