### ISSUE TITLE
AWSCognitoClientOptions doesn't contain a Region property (which is required by AWS)

### ISSUE THREAD

**Issue by evanirla** [aws/aws-aspnet-cognito-identity-provider#203]
https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/dc9b3f1ad1738d3bc0eb1db3e408f335d6fa2301/src/Amazon.AspNetCore.Identity.Cognito/Extensions/AWSCognitoClientOptions.cs#L18

When following the implementation guide, you get the following error when trying to authenticate a user: Amazon.Runtime.AmazonClientException: No RegionEndpoint or ServiceURL configured

**Comment by ashishdhingra** [comment]
Hi @evanirla,

Good afternoon.

Thanks for posting the question. Please confirm if you have configured region in `appsettings.Development.json` (for development environment) or `appsettings.json` as specified in the [Readme](https://github.com/aws/aws-aspnet-cognito-identity-provider#adding-amazon-cognito-as-an-identity-provider).

Thanks,
Ashish

**Comment by evanirla** [comment]
> Hi @evanirla,
> 
> Good afternoon.
> 
> Thanks for posting the question. Please confirm if you have configured region in `appsettings.Development.json` (for development environment) or `appsettings.json` as specified in the [Readme](https://github.com/aws/aws-aspnet-cognito-identity-provider#adding-amazon-cognito-as-an-identity-provider).
> 
> Thanks,
> Ashish

I have! As far as I’m concerned, the SDK is only reading 3 of the 4 required properties.

**Comment by ashishdhingra** [comment]
> > Hi @evanirla,
> > Good afternoon.
> > Thanks for posting the question. Please confirm if you have configured region in `appsettings.Development.json` (for development environment) or `appsettings.json` as specified in the [Readme](https://github.com/aws/aws-aspnet-cognito-identity-provider#adding-amazon-cognito-as-an-identity-provider).
> > Thanks,
> > Ashish
> 
> I have! As far as I’m concerned, the SDK is only reading 3 of the 4 required properties. In the logs it shows that the settings were read appropriately.

@evanirla Please specify `Region` in your appsettings.json as specified in the Readme and let me know if it works.

Thanks,
Ashish

**Comment by evanirla** [comment]
PEBKAC error, please ignore. Thanks for your help @ashishdhingra! Although I had everything in appsettings.json configured correctly, I had it in the wrong directory...
