### ISSUE TITLE
Use inclusive pronouns in documentation.

### ISSUE THREAD

**Issue by evanirla** [aws/aws-aspnet-cognito-identity-provider#204]
https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/dc9b3f1ad1738d3bc0eb1db3e408f335d6fa2301/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L142

Please use "they"/"them" instead of "he"/"him" when writing documentation. I identify as "he"/"him", but we can't expect that everyone does.

Thanks!

**Comment by normj** [comment]
Thanks for letting us know. I updated the comments I saw. Feel free to let me know if I missed any or open a pull request if you want to make the fixes yourself.
