### ISSUE TITLE
Any plans to support .NET 5.0?

### ISSUE THREAD

**Issue by flgatormike** [aws/aws-aspnet-cognito-identity-provider#205]

**Comment by ashishdhingra** [comment]
Hi @flgatormike,

Good morning.

The ASP.NET Cognito Identity provider targets `netstandard2.0` and it works for .NET 5.0 (also refer table at https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support which states that `netstandard2.0` supports .NET 5.0). Please advise if there is any specific issue that you are facing when using this library with ASP.NET Core Net 5.0 application. 

Thanks,
Ashish

**Comment by flgatormike** [comment]
I haven't figured out how to add this to my startup:
services.AddCognitoIdentity();

I get this error:
'IServiceCollection' does not contain a definition for 'AddCognitoIdentity'

I have used this library successfully with a ASP .NET Core 3.1 project with these using statements, but can't figure out how to make it work with a .NET 5.0 project.

using Amazon.CognitoIdentityProvider;
using Amazon.Extensions.CognitoAuthentication;

**Comment by flgatormike** [comment]
I got it running. Not sure what I was doing wrong, maybe I had the wrong version.
