### ISSUE TITLE
How to retrieve the list of all roles (groups)

### ISSUE THREAD

**Issue by stringit-mcagno** [aws/aws-aspnet-cognito-identity-provider#212]
By following the documentation at https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/docs/7-User%20Roles.md about managing roles, there's no indication about getting the list of all roles (groups).
I mean not only the ones assigned to a user, but the list of all roles in general.

I tried to use the original RoleManager, but when you access the Roles property, it returns an exception since the store doesn't implement the interface IQueryableRoleStore<>.

What's the right way to get the list of all roles by using the class of this repo?

This is a :question: general question

**Comment by ashishdhingra** [comment]
Hi @stringit-mcagno,

Good afternoon.

Thanks for posting guidance question. You might be right that this library does not support getting Cognito User pool groups out of the box. As a workaround, you might want to consume [AWSSDK.CognitoIdentityProvider](https://www.nuget.org/packages/AWSSDK.CognitoIdentityProvider/) package directly and use [AmazonCognitoIdentityProviderClient.ListGroupsAsync()](https://github.com/aws/aws-sdk-net/blob/925b48a3ee8532bd88f47a08aa9aa6d57b55feff/sdk/src/Services/CognitoIdentityProvider/Generated/_netstandard/AmazonCognitoIdentityProviderClient.cs#L4856) to list the groups associated with a user pool.

Thanks,
Ashish
