### ISSUE TITLE
Password policy is ignored by SDK

### ISSUE THREAD

**Issue by aussiearef** [aws/aws-aspnet-cognito-identity-provider#31]
If I create a User Pool in Cognito and set a loose password policy, then when I sign up a user with a simple password such as 123456, I will get an exception about the password not following the set policy.

However when AddCognitoIdentity is added with options which set the policy, the user can be created with a simple password.

Since the Cognito service is the decider of the password policy the SDK must fetch the policy from Cognito and user that rather than having some defaults.

**Comment by assyadh** [comment]
Hi,

Thanks for your feedback.

I think I see two different things at play here:

The #1 one is the client side validation which needs to mimic the user pool min/max password length: https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/samples/Samples/Areas/Identity/Pages/Account/Register.cshtml.cs#L50

The #2 one is that we actually retrieve the pool password policy and create a password validator based on it. It is injected in the CognitoUserManager and validates the password against the pool policy when creating new users:
https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoPasswordValidator.cs

Would you mind sharing the snippet of code of where you add the IdentityOptions to AddCognitoIdentity(). I may have a gap somewhere that I did not think about.

Thank you for providing me this valuable feedback.

Hamza.

**Comment by assyadh** [comment]
I am closing this issue, feel free to reopen it if you have more questions.
