### ISSUE TITLE
Link to ChangePassword fails because there is no ChangePassword Page in the Sample application

### ISSUE THREAD

**Issue by jmkelly** [aws/aws-aspnet-cognito-identity-provider#35]
Title pretty much explains it, but the following line fails just because there is no ChangePassword page / view in the sample app.

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/8cf35a83d69bb05047924071ece4f9f9fe301640/samples/Samples/Areas/Identity/Pages/Account/Login.cshtml.cs#L89

**Comment by assyadh** [comment]
Hi,

We are working on adding more examples to the sample app.

H

**Comment by Salcave** [comment]
Hello, I scaffolded a ChangePassword page using Identity, but when users enter their new password it doesn't get changed and receive a "Incorrect password" error even though their credentials are correct. Also, users receive a authorization code through sms at the same time. I get no errors on the console.

**Comment by assyadh** [comment]
Hi @Salcave, did you make the necessary changes in the controller to use the CognitoUserManager?

Also, in Cognito, there is a difference between changing a password: 

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L228

And Reseting a password (with a token, but not the old password):

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L273

**Comment by Salcave** [comment]
I believe so. Below is my CognitoUserManager: 

        private readonly CognitoUserManager<CognitoUser> _userManager;
        private readonly SignInManager<CognitoUser> _signInManager;
        private readonly ILogger<ChangePasswordModel> _logger;

        public ChangePasswordModel(
            UserManager<CognitoUser> userManager,
            SignInManager<CognitoUser> signInManager,
            ILogger<ChangePasswordModel> logger)
        {
            _userManager = userManager as CognitoUserManager<CognitoUser>;
            _signInManager = signInManager;
            _logger = logger;
        }

And this is the method that is suppose to change the password:

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(user, Input.OldPassword, Input.NewPassword);
            if (!changePasswordResult.Succeeded)
            {
                foreach (var error in changePasswordResult.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return Page();
            }

            await _signInManager.RefreshSignInAsync(user);
            _logger.LogInformation("User changed their password successfully.");
            StatusMessage = "Your password has been changed.";

            return RedirectToPage();
        }

**Comment by assyadh** [comment]
Can you double check the user status? your code looks correct at first sight

**Comment by Salcave** [comment]
The user is authenticated during the whole process, if that's what you're asking.

**Comment by Salcave** [comment]
@assyadh It seems like the password change issue was fixed with the Amazon.AspNetCore.Identity.Cognito update of 0.9.0.8, but users are still receiving an authorization code through sms after changing their password.
