### ISSUE TITLE
How to implement ChangePassword process

### ISSUE THREAD

**Issue by jmkelly** [aws/aws-aspnet-cognito-identity-provider#37]
Following on from https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/35, I'm attempting to implement a process for the account status FORCE_CHANGE_PASSWORD..

As far as I can tell, when getting a result from a login of `cognitoResult.RequiresPasswordChange`, the user is not authenticated.  I can't find a way to allow the user to reset their own password when we get in this state.  I've tried:

```
var user = await _userManager.FindByEmailAsync(Input.Email).ConfigureAwait(false);
user.ChangePasswordAsync(......)
```

This fails becuase the user isn't authenticated.

I've also tried to use the password reset process, but this also fails with the error 
`NotAuthorizedException: User password cannot be reset in the current state.`

The current state is FORCE_CHANGE_PASSWORD, with the email verified, as entered via the aws console.

Am I missing something obvious?

**Comment by assyadh** [comment]
Hi,

You can accomplish this by calling:

await _userManager.ChangePasswordAsync()

The user methods ofteb need the user to be already authenticated as they are decoupled with the Identity Provider mechanism. 

Please let me know if this fixes the issue.

H

**Comment by assyadh** [comment]
There might be a bug in the workflow, I'm currently looking into this. Will let you know asap.

**Comment by assyadh** [comment]
I have a PR out that should fix the issue, I will let you know when the new package is available on NuGet. Thanks for providing the feedback!

https://github.com/aws/aws-aspnet-cognito-identity-provider/pull/39/files

**Comment by assyadh** [comment]
Hi, 

This new version should solve the issue:

https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/0.9.0.1

Closing.

**Comment by jmkelly** [comment]
Hi H.

Apologies for my slow reply (I had notifications turned off), I can confirm with the new nuget package, I can now implement the ChangePassword funtionality using your suggested `_userManager.ChangePasswordAsync(.....)`.

Thanks very much!
