### ISSUE TITLE
Register or SignIn - OperationCanceledException: The operation was canceled

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#38]
I am trying to implement the this library and have taken the exact samples and simply added my AWS block to the appsetting.Development.json file:

`  "AWS": {
    "Region": "us-east-1",
    "UserPoolClientId": "<my client id>",
    "UserPoolClientSecret": "<my secret>",
    "UserPoolId": "<my user pool id>"
  }`

No matter whether I call CreateAsync or PasswordSignInAsync, after exactly 5 seconds I receive the error below.  Im pulling my hair out because something obviously bad is happening but the stack error is useless telling me it was cancelled.  Im certain its something stupid I missed but the error stack is not helpful at all.  I using .Net Core2, VS 2017 and everything compiles just fine and runs, no changes were made to the samples other than to add my AWS section to the appsettings:

`OperationCanceledException: The operation was canceled.
System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
System.Net.Http.HttpClient.GetStringAsyncCore(Task<HttpResponseMessage> getTask)
Amazon.Runtime.Internal.Util.AsyncHelpers+<>c__DisplayClass1_1<T>+<<RunSync>b__0>d.MoveNext()
Amazon.Runtime.Internal.Util.AsyncHelpers+ExclusiveSynchronizationContext.BeginMessageLoop() in AsyncHelpers.cs
Amazon.Runtime.Internal.Util.AsyncHelpers.RunSync<T>(Func<Task<T>> task) in AsyncHelpers.cs
Amazon.Util.AWSSDKUtils.DownloadStringContent(Uri uri, TimeSpan timeout, IWebProxy proxy) in AWSSDKUtils.cs
Amazon.Util.EC2InstanceMetadata.GetItems(string relativeOrAbsolutePath, int tries, bool slurp) in EC2InstanceMetadata.cs
Amazon.Util.EC2InstanceMetadata.get_IAMSecurityCredentials() in EC2InstanceMetadata.cs
Amazon.Runtime.DefaultInstanceProfileAWSCredentials.FetchCredentials() in DefaultInstanceProfileAWSCredentials.cs
Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentials() in DefaultInstanceProfileAWSCredentials.cs
Amazon.Runtime.DefaultInstanceProfileAWSCredentials.GetCredentialsAsync() in DefaultInstanceProfileAWSCredentials.cs
Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync<T>(IExecutionContext executionContext) in CredentialsRetriever.cs
Amazon.Runtime.Internal.RetryHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.RetryHandler.InvokeAsync<T>(IExecutionContext executionContext) in RetryHandler.cs
Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.MetricsHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Extensions.CognitoAuthentication.CognitoUserPool.GetPasswordPolicyTypeAsync()
Amazon.AspNetCore.Identity.Cognito.CognitoPasswordValidator.ValidateAsync(UserManager<CognitoUser> manager, CognitoUser user, string password)
Amazon.AspNetCore.Identity.Cognito.CognitoUserManager<TUser>.ValidatePasswordInternal(TUser user, string password)
Amazon.AspNetCore.Identity.Cognito.CognitoUserManager<TUser>.CreateAsync(TUser user, string password, IDictionary<string, string> validationData)
Samples.Areas.Identity.Pages.Account.RegisterModel.OnPostAsync(string returnUrl) in Register.cshtml.cs
+
                IdentityResult result = await _userManager.CreateAsync(user, Input.Password);
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod.Convert<T>(object taskAsObject)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.ExecutorFactory+GenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Internal.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

**Comment by assyadh** [comment]
Can you try the following:

**Comment by jlwhitfill** [comment]
Yes, Im running Visual Studio 2017, I have looked at the article and tried everything in it to no avail.  I didnt think it would work because it the cancellation error appears right at 5 seconds, which is not a long running item anyway and doesn't need to have the timeout extended.  Even with the changes the article proposes, using a webconfig or changing the PROGRAM.CS file and the UseKestrel function, it still shows the error at 5 seconds into the call  

I've implemented a complete Cognito authentication structure in a node.js setting and the login and register times are within a second or two max.  Im trying to get it all moved into a .NET server side setting and I just can get past this error above.  I even went as far as to create a brand new Cognito user pool with a basic setup, a new client id and secret and I still get this error.  It seems to be masking some other error, either a connection issue or a permission issue.

**Comment by jlwhitfill** [comment]
I now have it functioning, I went into the Nuget Package Manager and had to update one of my packages:

Microsoft.VisualStudio.Web.CodeGeneration.Design to the latest version.

That required me in install a few others with regards to Razor and then once that was all installed it magically started working.
