### ISSUE TITLE
Changing the phone number in the Identity scaffolded pages throws KeyNotFoundException: The given key 'phone_number' was not present in the dictionary error

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#47]
So I went ahead and scaffolded in the Identity pages for managing the user profile (Account/Manage/Index an corresponding management layout files).  I switched out all the injections to accommodate the Cognito User Manager and Sign in Manager object.  When I try to open the Index page as the user's profile, it throws the following error: 

`KeyNotFoundException: The given key 'phone_number' was not present in the dictionary.`

When the following line of code is run:

`var phoneNumber = await _userManager.GetPhoneNumberAsync(user).ConfigureAwait(false);`

and Im assuming that it also throws an error when you run this one also:

` var setPhoneResult = await _userManager.SetPhoneNumberAsync(user, Input.PhoneNumber).ConfigureAwait(false);`

The same calls for the email work just fine (GetEmailAsync and SetEmailAsync).  I figured these were just missed, but I will need them to function as I will be using SMS as well.  I could go the route of updating the attributes instead, but this makes life a lot easier.

Thanks for looking into this and hopefully Im not missing something.

**Comment by assyadh** [comment]
This is really weird, Can you please share a screenshot of your user attributes in Cognito?
phone_number is supposed to always be present.

**Comment by jlwhitfill** [comment]
I thought so too and I figured it out.  When I looked at the user attributes in Cognito there was NO "phone_number" attribute, so when there is no phone number on the user record and you call that, the phone_number attribute is not returned.  

However, when I load up my node project and add an actual phone number, the phone_number attribute THEN appears and the call works.  The GetPhoneNumberAsync call needs to catch that when there is no phone number initially on the user record, the phone_number attribute doesn't exist in the call you are making to Cognito.  See below:

Without the phone number set

![image](https://user-images.githubusercontent.com/43940326/51708255-aac9d480-1fe0-11e9-9e35-bf7f2899bd9a.png)

and with it set

![image](https://user-images.githubusercontent.com/43940326/51708322-e06ebd80-1fe0-11e9-8b2f-bae0072932d3.png)

**Comment by assyadh** [comment]
Right, on the first user subscription, it looks like there is an edge case where the phone number is not there.

**Comment by jlwhitfill** [comment]
The set works fine I just tested it.  Its just when the initial call is made when the there is no number it fails and should just trap that and return and empty string and then we are good.

**Comment by assyadh** [comment]
I have a PR in to fix this, and will let you know when it's available on NuGet

**Comment by assyadh** [comment]
This should fix the issue:

https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/0.9.0.4

Please let me know if it's not the case.

H.

**Comment by jlwhitfill** [comment]
This resolved the issue, thanks!
