### ISSUE TITLE
Is MultiFactor Authentication working in this library yet?

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#48]
Ive been able to implement MFA in the node.js world with Amplify but in switching over to the .NET Core2 world and this library, Im finding a lot of the base calls surrounding MFA or 2FA are not implemented.  I need to do SMS and TOTP.  In the node.js world using Amplify I can simply use setPreferredMFA (none, SMS or TOTP) and  VerifyTotpToken.  Then when its MFA I run setupTOTP, which generates 32 digit code that I can use to format for the Google Authenticator.

Can you get me started in the correct direction on what to call here (if it is fully implemented)?

**Comment by assyadh** [comment]
We currently only support SMS 2fa, TOTP will be supported in a later version.

When calling the PasswordSigninAsync method in the SigninManager you may be presented with an SignInResult.TwoFactorRequired result:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L157

This would trigger the send of an token via SMS, and completing the signing operation is done by calling:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L235

There is an example of this in the Samples:


https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L235

**Comment by jlwhitfill** [comment]
Excellent I figured that was the case, thanks
