### ISSUE TITLE
Set identity expiration/timeout

### ISSUE THREAD

**Issue by andyfurniss4** [aws/aws-aspnet-cognito-identity-provider#50]
Hi there,

I'm trying to set the identity expiration for my users but it doesn't seem to be working. I've set it to a two hour sliding expiration but I seem to get automatically logged out after about 30 minutes or so. Could you advise? Here is what I have currently:

```
services.AddCognitoIdentity();
services.AddSingleton<IAmazonCognitoIdentityProvider>(cognitoClient);
services.AddSingleton<CognitoUserPool>(userPool);

services
	.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
	.AddCookie();

services
	.ConfigureApplicationCookie(o =>
	{
		o.ExpireTimeSpan = TimeSpan.FromHours(2);
		o.SlidingExpiration = true;
		o.LoginPath = "/Identity/Account/Login";
		o.LogoutPath = "/Identity/Account/Logout";
	});
```

**Comment by andyfurniss4** [comment]
I believe this may be related to this answer on SO: https://stackoverflow.com/a/46223119/5392786

**Comment by assyadh** [comment]
Related issue https://github.com/aspnet/Identity/issues/1425#issuecomment-329372381

**Comment by assyadh** [comment]
I am able to reproduce the issue. looking deeper.

**Comment by assyadh** [comment]
Found it: https://github.com/aspnet/Identity/pull/1941

The fix was only added to Identity 2.2. I am adding it since our dependency points to 2.1.6.

I tested it and it fixes the issue.

**Comment by assyadh** [comment]
Thanks for the catch @andyfurniss4

**Comment by andyfurniss4** [comment]
Good stuff. Thanks for sorting @assyadh!

**Comment by assyadh** [comment]
https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/0.9.0.9 should solve the 30 minutes issue.
