### ISSUE TITLE
Result from PasswordSignInAsync does not contain an ERRORS property when it fails.  

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#51]
Int he case of many of the calls, when there is a failure, an ERRORS property is available for me to loop through and get the errors.  In the case of PasswordSignInAsync, when it fails (where SUCCEEDED = false).  I cant tell why it failed.  there are several properties like ISLOCKEDOUT, PASSWORDRESETREQUIRED, but if the failure is not due to any of those errors, I cant trap what caused it.  

For instance, I tried to login with a user email that doesnt exist or one that does exist with the incorrect password and I cant tell which is which.  I also cant tell if too many attempts were made.  Is this by design.  Im thinking I can just show them a generic error but I would like to log on my end that someone is attempting to login incorrectly too many times.

**Comment by jlwhitfill** [comment]
I think this is by design as the base _userManager object provides and ERRORS property but the _signInManager does not, but I will wait for confirmation

**Comment by assyadh** [comment]
Hi,

Yes this is by design, My understanding is that you don't want to surface too many errors to users that are not logged in.

The Entity Framework managers behave like that.

**Comment by jlwhitfill** [comment]
I figured as much and that is correct, I dont want to tell them its a bad user or bad password or that the user even exists.  It was more for my logging underneath so I can trend what is happening.  Thanks anyway.
