### ISSUE TITLE
How do I retrieve the Access Token from the UserManager?

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#56]
I need to pass the Access token to my API Lambda functions and I Im kind of scratching my head on how to get it once logged in.  I see there is a function called:

GetAuthenticationTokenAsync

but when I try to use it I get a NotSupportedException.

**Comment by assyadh** [comment]
Once you Sign in, the CognitoUser instance has the AccessToken object populated. I am looking into incorporating Identity apis with this.

**Comment by assyadh** [comment]
See: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L40

**Comment by jlwhitfill** [comment]
Thanks, I realized after I sent it that it was probably incorporated in the CognitoUser, but figured I would leave it there since the Identity APIs also have an option for it.  Thanks!

**Comment by assyadh** [comment]
I have a PR in to expose tokens through HttpContext.GetTokenAsync(). I will let you know when this is released

**Comment by assyadh** [comment]
Hi, 0.9.0.7 now exposes the token through HttpContext.GetTokenAsync(): https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoSigninManager.cs#L141

https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/0.9.0.7

**Comment by jlwhitfill** [comment]
The Context.GetTokentAsync is now working as expected, however in one of your previous comments here you said the CognitoUser.SessionTokens are being populated as well.  In checking this. I am finding that it never gets set and is always null when I check it after login.
