### ISSUE TITLE
Confirming Phone number throws an an error

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#63]
When I attempt to confirm a phone number change with a verification code using

`await _userManager.ConfirmPhoneNumberAsync(user, code)`

I receive the following error:

```
NullReferenceException: Object reference not set to an instance of an object.
Amazon.AspNetCore.Identity.Cognito.CognitoUserStore<TUser>.VerifyUserAttributeAsync(TUser user, string attributeName, string code, CancellationToken cancellationToken)
Client.WebApp.Controllers.AccountController.Confirm(Confirm model) in AccountController.cs
+
                        result = await _userManager.ConfirmPhoneNumberAsync(user, model.Code).ConfigureAwait(false);
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
NToastNotify.NtoastNotifyAjaxToastsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass5_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
The user manager, user and code are all valid and it appears its blowing up trying to verify the phone attribute, but that exists too in my user below:

![image](https://user-images.githubusercontent.com/43940326/52577806-1b922e80-2de0-11e9-8000-28ad7be5b2dc.png)

**Comment by jlwhitfill** [comment]
FYI, the call `ConfirmEmailAsync `also produces the same error

**Comment by jlwhitfill** [comment]
Also I need a way to resend the phone and email change confirmation codes like you did with the `ResendSignupConfirmationCodeAsync `option.  If I try to call the  `SendEmailConfirmationTokenAsync `or `SendPhoneConfirmationTokenAsync`, they throw the and error:

```
NullReferenceException: Object reference not set to an instance of an object.
Amazon.AspNetCore.Identity.Cognito.CognitoUserStore<TUser>.GetUserAttributeVerificationCodeAsync(TUser user, string attributeName, CancellationToken cancellationToken)
Wamba.Client.WebApp.Controllers.AccountController.Login(Login model) in AccountController.cs
+
                        var result2 = await _userManager.SendEmailConfirmationTokenAsync(user).ConfigureAwait(false);
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
```

**Comment by assyadh** [comment]
You are using the correct API, but your CognitoUser instance probably does not have a session token object populated.

This Cognito api can only be called with a Cognito logged-in user.

Try setting up the token on the user (by signing in, or retrieving the token on the context).

H.

**Comment by jlwhitfill** [comment]
I am signed in, I used the `_signInManager.PasswordSignInAsync` method and its not populating the session of the cognito user.  If I retrieve the user, right after the call above and check the cognitoUser. SessionTokens, its null.  Im I not doing something correct?  When you say retrieving the token on the context, Im not sure what you mean

**Comment by assyadh** [comment]
You don't need to retrieve it, you can use the same instance as it gets updated.

**Comment by assyadh** [comment]
You can get the access token of the currently signed in user by calling HttpContext.GetTokenAsync("access_token")

**Comment by jlwhitfill** [comment]
Maybe I am misunderstanding the process of logging in.

I use _signInManager.PasswordSignInAsync, its gives me a SUCCEEDED response.

How do I retrieve the CognitoUser immediately after that which has a session object populated?

When I am on other pages, I have been using:

         `var user = await _userManager.GetUserAsync(User).ConfigureAwait(false);`

where User is the HttpContextUser value.  From what I am feeling in my code, this is not the correct method.  IS there a difference between a user being signed in and authenticated. 

I think I am misunderstanding the flow of the login and how to easily retrieve the cognito user properly.

**Comment by assyadh** [comment]
There is an overload on PasswordSignInAsync that allows you to sign in with a CognitoUser object. this object will get tokens populated once signed in.

Example:

`var user = await _userManager.FindByIdAsync(Input.UserName);`

`
var result = await _signInManager.PasswordSignInAsync(user, Input.Password, Input.RememberMe, false);`

**Comment by jlwhitfill** [comment]
Ok I was able to login a user in with a populated session as you stated above, but here is my dilemma.  I then move to the profile page after logging in, HOW do I get that same user back with a populated session so I can call _`userManager.ConfirmPhoneNumberAsync(user, code)`.  I have to have a session in place on the CognitoUser for this to happen but if I call `var user = await _userManager.GetUserAsync(User)`, I get back a user without a session.  Now you say call the HttpContextObject to retrieve the tokens, but how to I populate the CognitoUser with those.  I can get them from HttpContext.GetTokenAsync("access_token") but that does me no good as I need them to be populated in the CognitoUser before I pass it to several procedures that require a logged in user.

**Comment by assyadh** [comment]
Hi @jlwhitfill,

I know have a better grasp of your issue. I am thinking of a change that would automatically populate the tokens if you are on a different webpage than the initial one.

This is a difference due to the nature of Cognito vs SQL Server. SQL Server has the tokens in the table, so each time you query FindById() for instance you get a set of tokens if availables.

I will let you know how my testing goes.

H.

**Comment by jlwhitfill** [comment]
Right as the original base Identity works differently than Cognito.   Your change would be perfect and Im glad you understand, I was starting to pull my hair out as I need that session available on most pages either for congito functions for to retrieve the access token for my Lambda function calls.  Can you make it populate the tokens anytime I do ANY find by?  e.g. FindByEmail, FindById, etc?

**Comment by assyadh** [comment]
Yes that's what I plan to do

**Comment by assyadh** [comment]
https://github.com/aws/aws-aspnet-cognito-identity-provider/pull/64

**Comment by jlwhitfill** [comment]
Thanks Ill wait for the approval, merge and subsequent build

**Comment by assyadh** [comment]
Hi,

0.9.0.8 Should fix the issue.

https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/0.9.0.8
