### ISSUE TITLE
The operation was canceled.

### ISSUE THREAD

**Issue by flgatormike** [aws/aws-aspnet-cognito-identity-provider#65]
Hi,
I downloaded the sample app, and changed the AWS settings to the ones below
(I changed a bunch of letters and numbers so these aren't real credentials here)

And I get this error when I try to log in:
OperationCanceledException: The operation was canceled.
System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)

Any idea what I am doing wrong?

    "Region": "us-east-1",
    "UserPoolClientId": "6i5aljnb2k7ckl4ye5ko32lk1y",
    "UserPoolClientSecret": "47jickio4legsvhcrfg0g67p890ndt5ouspl0i2lop8a3juht24gj",
    "UserPoolId": "us-east-1_ws5AjVfgt"

**Comment by assyadh** [comment]
Probably related to https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/41

I am currently working on it. Closing this issue to keep track on the other one.
