### ISSUE TITLE
Possible to retrieve user created date?

### ISSUE THREAD

**Issue by andyfurniss4** [aws/aws-aspnet-cognito-identity-provider#68]
Me again.

I can see in Cognito that there's a 'Created Date' field but I can't figure out how to get hold of this value programatically. It's not returned in the collection attributes and I can't see a method to get it explicitly. Is it possible?

**Comment by assyadh** [comment]
Hi,

Iirc, the creation date is not a cognito attribute, it is rather returned by calling the AdminGetUser api: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_AdminGetUser.html

You can look into implementing this by yourself if you are in a hurry (for this, use the CognitoUserPool instance available through the ServiceCollection, it contains the pool id property).

I am pinning this issue to track adding it into the CognitoUser class and the FindBy* methods of the UserManager but can not give an eta

https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs

**Comment by tachyon1337** [comment]
This issue can be easily remedied by simply creating a created_at custom attribute and setting the value when creating the user.

**Comment by assyadh** [comment]
I'll close this, as a workaround is available, we may pull this into v2
