### ISSUE TITLE
Resetting the user password when the user is authenticated and has session tokens

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#73]
So I have a user profile page and the user is authenticated with a full session.  I have a section to offer a password reset, but the only option I can see for resetting the password is one that requires a code, which I thought was only necessary if the user is not authenticated.

In the Node.js Amplify version I wrote, I can change the user's password if they are authenticated and not require a verification code.

Is there a way to not make the user have to switch screens and enter an authenitcation code?  I implemented it with that process and it works, just seems like overkill if the user changing the password is authenticated, unlike when you do a forgot password and then utilize the resetpasswordasync.

I tried the RemovePassword and AddPassword and that threw errors it was not implemented.

**Comment by assyadh** [comment]
Calling the UserManager.ResetPasswordAsync(TUser user) Admins reset the password by sending a token (no need to be logged in, this is an Admin operation):

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L294

Calling  UserManager.ResetPasswordAsync(TUser user, string token, string newPassword) changes the password using the token retrieved above: (this also does not require to be logged in, the token allows the password to be changed):

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoUserManager.cs#L278

UserManager.ChangePasswordAsync(TUser user, string currentPassword, string newPassword) 
just changes the password, you have to be logged in.

**Comment by jlwhitfill** [comment]
thanks this worked
