### ISSUE TITLE
Retrieving userName and sub immediately after registration. 

### ISSUE THREAD

**Issue by josephd9** [aws/aws-aspnet-cognito-identity-provider#74]
I'm trying to get the user name and the user's sub right after registration, right after "  await _signInManager.SignInAsync(user, isPersistent: false);". I can't seem to find the right way to do this. 

Also, which is better for storing a unique user identifier in my database, the sub or the user name?

**Comment by assyadh** [comment]
Hi,

You can call userManager.GetClaimsAsync() for this:

https://github.com/aspnet/Identity/blob/eb3ff7fc32dbfff65a1ba6dfdca16487e0f6fc41/src/Microsoft.Extensions.Identity.Core/UserManager.cs#L1128

H.

**Comment by josephd9** [comment]
You are a gentleman and a scholar. Thank you!

**Comment by assyadh** [comment]
The sub is the unique identifier on Cognito's side for a user in the pool.
