### ISSUE TITLE
Refreshing the Access token

### ISSUE THREAD

**Issue by jlwhitfill** [aws/aws-aspnet-cognito-identity-provider#76]
So from my reading and by experience the Access token is good for one hour.  After that you need to refresh it with the Refresh token.  I know the Amplify node.js library automatically does it.

Does that happen with this library?  If not what is the flow or process for checking it and refreshing it and what can I call here to do that.  I'm not seeing the ability to do that anywhere (of course I may just be blind).  I was hoping that when I do a _userManager.FindByXXXX, that the tokens would be refreshed for me, but the user manager code is not showing that is happening.

Thoughts?

**Comment by assyadh** [comment]
Hi,

You can call CognitoUser.StartWithRefreshTokenAuthAsync() to implement this.

https://github.com/aws/aws-sdk-net-extensions-cognito/blob/a6c789d586e11785288e9d7d7fa39537dbcf5e14/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs#L217

**Comment by assyadh** [comment]
There might be a way to automate this within Identity, I'm looking into this.

**Comment by tachyon1337** [comment]
```cs
var req = new AdminInitiateAuthRequest();
req.UserPoolId = _pool.PoolID;
req.ClientId = _pool.ClientID;
req.AuthFlow = AuthFlowType.REFRESH_TOKEN_AUTH;
req.AuthParameters.Add("REFRESH_TOKEN", refreshToken);
var result = await _identityProvider.AdminInitiateAuthAsync(req);
var authResult=result.AuthenticationResult;
//authResult.AccessToken --> new access token
//authResult.IdToken --> new id token
//authResult.RefreshToken --> new refresh token

```

will give you new access and id tokens, but the new refresh token is empty. Is this an app client oauth flow misconfiguration(be default, there is no oauth flow checked in the app client console), or is it a matter of only getting a new refresh token if the old one is expired?

**Comment by jlwhitfill** [comment]
For me its just refreshing once it expired or possibly catching it and refreshing it before it expires

**Comment by tachyon1337** [comment]
> For me its just refreshing once it expired or possibly catching it and refreshing it before it expires

I looked over the docs and did some testing. A SignIn will give you a new accessToken, a new idToken and new refreshToken. The access tokens are good for one hour, at which point the client will need to pass up the cached refreshToken to get a new set of access tokens. The Refresh Token AuthFlow will only send down access tokens.By default, a refresh token is good for 30 days of reuse to fetch new access tokens. When the refresh token expires, then the user must sign in again to the app.

AspnetCore Identity will only "automagically" handle a JwtBearer authentication scheme--which is different than the default cookie based authentication scheme--with the proper configuration, which is different than the Sample App configuration in this repository.  The biggest problem is that the cognito access token will not work out the box with `[Authorize(Roles="myRole")]` attribute. Out of the box requires the access token to contain a roles property representing a user's role claims. Cognito tokens, however,  represent the group/role claims with a `"cognito:groups"` property. So, attempting to fine graining authorization by role in the Authorize attribute will result in a 403 error. So, to get around this, you either have to write a custom policy authorization handler or use a Pre Token Generation Lambda function to map `"cognito:groups"` property to a `roles` property in the token, which I haven't figured out how to do yet. Another option perhaps would be to do a Post Token Generation transformation on the server(decode the token, map a roles property for the user roles claims and re-encode before sending to the client).

**Comment by jlwhitfill** [comment]
Forutnately in my case I dont need to get granular with roles, but that's interesting how the cognito does and does not map properly to the identity provider.  Just thought it would be nice if it would handle the token refresh automatically like Amplify does.

**Comment by jlwhitfill** [comment]
Also in many of the readings when you refresh the tokens, it doesnt return a  new refresh token, but you can keep using that token within its default 30 day time frame.  Apparently you have to somehow store the refresh token your self which to me is odd

**Comment by jlwhitfill** [comment]
@assyadh I tried using the command you gave me:

`await user.StartWithRefreshTokenAuthAsync(new InitiateRefreshTokenAuthRequest() { AuthFlowType = AuthFlowType.REFRESH_TOKEN_AUTH }).ConfigureAwait(false);`

and it immediately throws an exception of an Invalid Refresh token:

`NotAuthorizedException: Invalid Refresh Token.
Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in HttpErrorResponseExceptionHandler.cs
Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in ErrorHandler.cs
Amazon.Runtime.Internal.ErrorHandler.InvokeAsync<T>(IExecutionContext executionContext) in ErrorHandler.cs
Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync<T>(IExecutionContext executionContext) in CredentialsRetriever.cs
Amazon.Runtime.Internal.RetryHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.RetryHandler.InvokeAsync<T>(IExecutionContext executionContext) in RetryHandler.cs
Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.CallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Runtime.Internal.MetricsHandler.InvokeAsync<T>(IExecutionContext executionContext)
Amazon.Extensions.CognitoAuthentication.CognitoUser.StartWithRefreshTokenAuthAsync(InitiateRefreshTokenAuthRequest refreshTokenRequest)
Wamba.Client.WebApp.Controllers.ProfileController.Profile() in ProfileController.cs
+
            var authResponse2 = await user.StartWithRefreshTokenAuthAsync(new InitiateRefreshTokenAuthRequest() { AuthFlowType = AuthFlowType.REFRESH_TOKEN_AUTH }).ConfigureAwait(false);
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
NToastNotify.NtoastNotifyAjaxToastsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass5_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

Yet I look at the user's session tokens and it has a complete set of session tokens, including a refresh token that is not expired.  I am trying to refresh before the Access token is expired if that means anything.  I am trying this right after I login and have a clean set of tokens.

**Comment by tachyon1337** [comment]
> Apparently you have to somehow store the refresh token your self which to me is odd

For javascript clients operating in the browser, the storage mechanism is localStorage, which is what Amplify uses. It doesn't take long to write your own javascript api client to seamless negotiate token expiration.

**Comment by tachyon1337** [comment]
> I am trying to refresh before the Access token is expired if that means anything. I am trying this right after I login and have a clean set of tokens.


[Use the code I wrote here for getting new access tokens from a refresh token](https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/76#issuecomment-469436895)

The basic workflow is:
(1) pass the tokens down to the client on sign up
(2) client caches the tokens in localStorage
(3) In a service call, have a 401 response handler
(4) 401 response handler grabs the refresh token from localStorage and sends it up to a RefreshToken api endpoint
(5) RefreshToken endpoint uses `_identityProvider.AdminInitiateAuthAsync` to get a new set of access tokens and passes them back down to the client
(6) 401 response handler replaces the access tokens in cache and reinitiates the original call
(7) if the RefreshToken api endpoint errors because the refresh token is no longer valid, the 401 response handler passes an error back to the callback of the initial request, which should then prompt the app to redirect to the signin page.

**Comment by jlwhitfill** [comment]
While that looks to work, I'm not sure I want to be initiating Admin commands from my user portal.  Admin commands are for internal Admin consoles to deal with all the user issues internally.  The above method @assyadh posted seems like a better approach, not to demean what you did @tachyon1337 as you have gotten it working for your needs.  I was just hoping there was a non-admin approach

**Comment by jlwhitfill** [comment]
I found the answer to this @assyadh, I stumbled across this post:

https://stackoverflow.com/questions/46879876/aws-cognito-invalid-refresh-token

If I turn off the REMEMBER DEVICES, then it works, its expecting a device key which I can get from:

`CognitoUser.Devices.DeviceKey`

but I have no where to send that in the `StartWithRefreshTokenAuthAsync `request.

In looking at another issue with the extensions I see someone else having this issue and you messaged on it 5 days ago you would look into, so these are related:

https://github.com/aws/aws-sdk-net-extensions-cognito/issues/24

Somehow I have to be able to send in the AuthParams with the device key in it if I want to remember devices, which I do.

**Comment by assyadh** [comment]
Hi,

I am currently out of the office. Thanks for the feedback, I'll have a look when I'll be back late next week. 

Thanks again, 

H.

**Comment by tachyon1337** [comment]
> While that looks to work, I'm not sure I want to be initiating Admin commands from my user portal. 

`_identityProvider.InitiateAuthAsync`

works, too.

**Comment by jlwhitfill** [comment]
That works too, however, it becomes an issue when I add the [Authorize] attribute to the controller, the CookieAuthorization takes over and redirects to the login page immediately.  I can trap the 401 in the Startup.cs, but I cant seem to implement the usermanager or signinmanager within the startup.cs to refresh the token.  Its almost as if I need to remove the [AUTHORIZE] attribute and handle it in each controller manually which seems like overkill, especially if I have to do it in multiple controllers that require auth.

I would rather handle it in the middleware section of the startup.cs.  Not really sure how to implement it.  The way that is described above with the IntiaiteAuthAsync doesnt seem to fit here when using the Identity provider that this library is based on.  With CookieAuth, the 401 is replaced with a 301 redirect to the login page.

What I want to do is trap the 401 error in the auth middleware, and attempt to refresh the token, if I can, then I proceed to where the user was attempting to direct themselves too.  If the refresh token is expired then I simply let the cookie auth take over and redirect to the login page.

**Comment by tachyon1337** [comment]
> That works too, however, it becomes an issue when I add the [Authorize] attribute to the controller,

The Refresh Token endpoint should be `AllowAnonymous`.

>  the CookieAuthorization takes over and redirects to the login page immediately. I can trap the 401 in the Startup.cs

You have to change the default authentication schema in `ConfigureServices` to use jwt tokens to override the default behavior of 302 redirects with 401 responses for unauthorized requests. Something like:

```cs
services.AddAuthentication(options =>
{
      options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
      options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
  }).AddJwtBearer(options =>
{
       options.TokenValidationParameters = tokenValidationParams;
});

**Comment by jlwhitfill** [comment]
Its not an API, its a pure MVC website that calls APIs from a separate project.  But I cant set the cookie expiration more than 1 hour, because the Cognito session tokens dont last for more than an hour right?

**Comment by tachyon1337** [comment]
> Its not an API, its a pure MVC website that calls APIs from a separate project. But I cant set the cookie expiration more than 1 hour, because the Cognito session tokens dont last for more than an hour right?

Hmm, glancing at the source code, you may be right. The Cognito SignInManger override method for SignInAsync
```cs
public override Task SignInAsync(TUser user, bool isPersistent, string authenticationMethod = null)
{
            // Populating the tokens to be retrieved when calling Context.GetTokenAsync(OpenIdConnectParameterNames.AccessToken).
            var authenticationProperties = new AuthenticationProperties
            {
                IsPersistent = isPersistent,
                AllowRefresh = true,
                ExpiresUtc = user.SessionTokens?.ExpirationTime,
                IssuedUtc = user.SessionTokens?.IssuedTime
            };

            authenticationProperties.StoreTokens(new List<AuthenticationToken>()
            {
                new AuthenticationToken()
                {
                    Name = OpenIdConnectParameterNames.AccessToken,
                    Value = user.SessionTokens?.AccessToken
                },
                new AuthenticationToken()
                {
                    Name = OpenIdConnectParameterNames.RefreshToken,
                    Value = user.SessionTokens?.RefreshToken
                },
                new AuthenticationToken()
                {
                    Name = OpenIdConnectParameterNames.IdToken,
                    Value = user.SessionTokens?.IdToken
                }
            });

            return SignInAsync(user, authenticationProperties, authenticationMethod);
 }
```

appears to pass in the Cognito User Session values into a created instance  of AuthenticationProperties and then calls the base AspNetCore SignInAsync overload method with that instance. I'm not using cookie auth with Cognitio, so I haven't tested it. But you could circumvent that by directly calling the AspNetCore SignInAsync overload with your own instance of `AuthenticationProperties`

**Comment by assyadh** [comment]
The version 0.9.0.13 should fix this as it implements the RefreshSigninAsync method

**Comment by jlwhitfill** [comment]
This doesnt look like it will work correctly if you have remember devices turned on.  The process also requires a device id to be sent in the auth params which is not referenced in any of this code.  When the remember devices is turned off, the StartWithRefreshTokenAuthAsync works correctly.  A few messages above, I had done some testing and replied:

[Previous Message](https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/76#issuecomment-470723245)
