### ISSUE TITLE
No definition for CognitoAttributesConstants when upgrading to 0.9.0.11 

### ISSUE THREAD

**Issue by josephd9** [aws/aws-aspnet-cognito-identity-provider#77]
I was on .9 then upgraded to .11 and the class CognitoAttributesConstants became undefined. I downgraded to .10 and it worked. I tried but could not find the necessary reference to use this class while using .11.

**Comment by assyadh** [comment]
Hi,

Yes they have been renamed to CognitoAttribute:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/src/Amazon.AspNetCore.Identity.Cognito/CognitoAttribute.cs

There is also a constructor that allows you to expend the class and build your own attribute now.

Sorry about that but while we are still in dev preview there might be some breaking changes.
