### ISSUE TITLE
email confirmation

### ISSUE THREAD

**Issue by ghendo** [aws/aws-aspnet-cognito-identity-provider#78]
In CognitoSignInManager
method
        protected override async Task<SignInResult> PreSignInCheck(TUser user)
        {
            // Checks for email/phone number confirmation status
            if (!await CanSignInAsync(user).ConfigureAwait(false))
            {
                return SignInResult.NotAllowed;
            }
            if (await IsPasswordChangeRequiredAsync(user).ConfigureAwait(false))
            {
                return CognitoSignInResult.PasswordChangeRequired;
            }
            if (await IsPasswordResetRequiredAsync(user).ConfigureAwait(false))
            {
                return CognitoSignInResult.PasswordResetRequired;
            }
            return null;
        }
Does not appear to actually check email confirmations status
If email is not confirmed signIn is allowed

**Comment by assyadh** [comment]
Does your pool actually prevents non confirmed email from signing in?

**Comment by ghendo** [comment]
So not sure what you mean by this.
If you mean there is a setting in Cognito that is set to allow or prevent login for unconfirmed user, I cant find such a setting. 
If you mean the system should allow sign in for unconfirmed user I get an exception on
                var result = await _signInManager.PasswordSignInAsync(Input.Email, Input.Password, Input.RememberMe, lockoutOnFailure: false).ConfigureAwait(false);
when unconfirmed user tries to sign in

**Comment by tachyon1337** [comment]
`CognitoUser` has a `Status` property and an `email_verified` attribute that you can directly check in an `if...else` statement.

**Comment by assyadh** [comment]
Closing. Feel free to reopen if you need help
