### ISSUE TITLE
Null Exception Error for UserManager FindBy* methods

### ISSUE THREAD

**Issue by tachyon1337** [aws/aws-aspnet-cognito-identity-provider#81]
```cs
var user = await _userManagerFindByName(username);
```

generates the null exception error below

```bash
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Amazon.AspNetCore.Identity.Cognito.CognitoUserManager`1.PopulateTokens(TUser user, String claimType, String claimValue)
```

The User Pool is set to allow sign in by username and verified email. However, everything else that I've tested seems to work. GetUsersAsync() works, CreateUser, AddToRoleAsync, getting tokens... all work.

**Comment by klaytaybai** [comment]
Hi @tachyon1337, I wasn't able to reproduce this issue.  Are you still having issues with it?  Which package versions are you using?

**Comment by klaytaybai** [comment]
Could you provide a more complete stack trace, too?

**Comment by tachyon1337** [comment]
> I wasn't able to reproduce this issue. 

Probably because I'm running my tests from a console app. I looked at the source code for CognitioUserManager and it appears the `PopulateTokens` method has a reliance on an injected `IHttpContextAccessor` in order to try to construct a ClaimsPrinciple on the retrieved user.  Obviously, in a console environment, the HttpContext property will be null, hence the null exception.  It looks like you did null checking safeguards on everything but the HttpContextAccessor. There are scenarios(e.g, User Administration) where you might want to use the Identity Framework from the command line.

**Comment by assyadh** [comment]
If you are running from a console app then the HttpContext is most likely null as you said.

I will add some safeguarding around that property

**Comment by assyadh** [comment]
This should fix it: https://www.nuget.org/packages/Amazon.AspNetCore.Identity.Cognito/0.9.0.12
