### ISSUE TITLE
Confirm Email Change

### ISSUE THREAD

**Issue by Salcave** [aws/aws-aspnet-cognito-identity-provider#83]
Hi, so I'm trying to enable email change on my app, and I managed to create an email confirmation page by replicating components from the ConfirmAccount and ConfirmEmail models to create the OnPostAsync method below: 

```
        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Name).Value;

                var user = await _userManager.FindByIdAsync(userId);
                if (user == null)
                {
                    return NotFound($"Unable to load user with ID '{userId}'.");
                }

                var result = await _userManager.ConfirmEmailAsync(user, Input.Code);
                if (!result.Succeeded)
                {
                    throw new InvalidOperationException($"Error confirming email for user with ID '{userId}':");
                }
                else
                {
                    return returnUrl != null ? LocalRedirect(returnUrl) : Page() as IActionResult;
                }
            }

            return Page();
        }
    }
```
The problem, though, is that I'm receiving a `"Failed to verify the attribute for the Cognito User : 1 validation error detected: Value at 'accessToken' failed to satisfy constraint: Member must satisfy regular expression pattern: [A-Za-z0-9-_=.]+"` error when `ConfirmEmailAsync` is called and I'm not sure why.

**Comment by jlwhitfill** [comment]
Are you sure your user is currently authenticated when you do this?  What you have above is similar to what I have and mine works ok.  When you call the FindByIdAsync method is should return a a user that is authenticated for the ConfirmEmailAsync process to work.

The way you know the user is authenticated is if you look at the CongitoUser returned by the FindByIdAsync method:

`user.SessionTokens`

should not be null, if it is your user is authenticated properly.  They user has to be currently authenticated for the email change process to work.  The fact its erring on the Access token tells me your user.SessionTokens is currently null

**Comment by Salcave** [comment]
Wow, that was the issue. I hadn't logged the user out in three days and the tokens had expired. Thanks!

**Comment by jlwhitfill** [comment]
Anytime, Im glad I could assist as Im constantly looking for it myself on other issues :)

**Comment by klaytaybai** [comment]
@jlwhitfill, thanks for helping out :).
