### ISSUE TITLE
Use multiple user pools

### ISSUE THREAD

**Issue by ghendo** [aws/aws-aspnet-cognito-identity-provider#84]
If I wanted to use multiple User Pools in my application what would I do to implement that?

**Comment by klaytaybai** [comment]
Hi @ghendo, I don't think this library supports that right now.  Can you tell us more about your particular requirements?  There may be other solutions that we could provide some guidance on.

**Comment by ghendo** [comment]
> Hi @ghendo, I don't think this library supports that right now. Can you tell us more about your particular requirements? There may be other solutions that we could provide some guidance on.

I am doing an application dot net core that has multiple sites in one app and would like to keep the users separate in different pools.

**Comment by tachyon1337** [comment]
> If I wanted to use multiple User Pools in my application what would I do to implement that?

Roll a custom abstraction and implementation around the `IAmazonCognitoIdentityProvider` in the AWS SDK. The IdentityProvider Client's constructor signature
```cs
public AmazonCognitoIdentityProviderClient (string awsAccessKeyId, string awsSecretAccessKey, RegionEndpoint region)
```
doesn't rely on any appclient or userpool settings; those values are set in the request object params in the individual client api calls. So it would be possible to do it consistent with dependency injection but not using the AspNetCore Identity abstraction. The CognitoUserStore relies on an injected UserPool configured in StartUp.

**Comment by assyadh** [comment]
Hi,

This is currently not supported. In essence, the Identity membership system is designed to hit one source of data (one SQL database by default).

You could get around this, but you would have to do dual reads for a lot of the manager methods (FindByEmail etc).

Also you would have to do some arbitrage on where you want to do the writes.

as @tachyon1337 commented, one way is to implement your own IAmazonCognitoIdentityProvider and override the different methods we use in the stores layers, but it would be cumbersome. You will also need to do the same with the CognitoUserPool class.

**Comment by assyadh** [comment]
Resolving, feel free to reopen if you have any other questions
