### ISSUE TITLE
[Authorize(Roles = "<Role>")] doesn't work

### ISSUE THREAD

**Issue by neil-rubens** [aws/aws-aspnet-cognito-identity-provider#86]
It would be nice to do role based authorization via [Authorize(Roles= "{Role}")]; however currently it doesn't work; in part probably because cognito (groups/roles) are mapped to `cognito:groups`.

p.s. it's one of the examples on the announcement page, so seems like it ought to work: https://aws.amazon.com/blogs/developer/now-generally-available-the-asp-net-core-identity-provider-for-amazon-cognito/

Is there a way to get it to work?
p.s. besides writing custom policy

p.s. also posted this question on https://stackoverflow.com/questions/55234563/role-based-authorization-for-aws-cognito

**Comment by tachyon1337** [comment]
> in part probably because cognito (groups/roles) are mapped to cognito:groups

That is the sole reason.

> p.s. besides writing custom policy

Not that I know of. I had to write a custom authorization handler, attribute, policy provider and requirement to implement group(role) based authorization. Something like:

```cs
[GroupAuthorize("Writer")]
[HttpGet("{id}")]
public async Task<string> Get(string id)
{     
}

```

**Comment by neil-rubens** [comment]
> > in part probably because cognito (groups/roles) are mapped to cognito:groups
> 
> That is the sole reason.
> 
> > p.s. besides writing custom policy
> 
> Not that I know of. I had to write a custom authorization handler, attribute, policy provider and requirement to implement group(role) based authorization. Something like:
> 
> ```cs
> [GroupAuthorize("Writer")]
> [HttpGet("{id}")]
> public async Task<string> Get(string id)
> {     
> }
> ```

Thanks.  Also `GroupAuthorize`  is a nice name for the policy.   Looks like a similar issue was also encountered with AD Groups: https://www.moonlightbytes.com/blog/mvc-windows-authentication-with-ad-groups

**Comment by tachyon1337** [comment]
> Thanks. Also GroupAuthorize is a nice name for the policy.

Yeah, the trick is get it to work just like roles,  that is, a single policy can handle an arbitrary comma delimited string of groups in the attribute constructor without having to wire up a separate policy in startup for each group or group combinations.

**Comment by neil-rubens** [comment]
> Yeah, the trick is get it to work just like roles, that is, a single policy can handle an arbitrary comma delimited string of groups in the attribute constructor without having to wire up a separate policy in startup for each group or group combinations.

I think this could be done with the [Custom Authorization Policy Providers](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-2.2)

**Comment by tachyon1337** [comment]
> I think this could be done with the Custom Authorization Policy Providers

Yeah, that's exactly how I did it.

**Comment by rayhaanq** [comment]
I've got the same issue, Adding Role = "Admin" returns 403 error even if the user is part of that group

**Comment by ashishdhingra** [comment]
Hi @neil-rubens,

I came across the useful article [ASP.NET Core with AWS Lambda and Cognito](https://criticalhittech.com/2019/02/19/asp-net-core-with-aws-lambda-and-cognito/) which might be useful for configuring Cognito Group based authorization in an ASP.NET Core application. It has a section **Groups and Policies** which provides the following details to add a custom policy.

_You can use [Authorize] to ensure that only logged-in users can access the Page/Controller/Route. However you’d probably like more fine-grained control, so for that you can add users to Cognito Groups. On the ASP.NET Core app, those groups are sent as part of the user Claims. You can create authorization polices during the Startup.Configure method as follows:_
```C#
services.AddAuthorization(options =>
{
    options.AddPolicy("AdminOnly", policy =>
    policy.RequireAssertion(context =>
    context.User.HasClaim(c => c.Type == "cognito:groups" && c.Value == "Admin")));
});
```
_This creates a policy requiring the logged in user to be part of the Cognito group Admin. To use this on a Page/Controller/Route, refer to the policy name in the Authorize attribute:_
```C#
[Authorize(Policy = "AdminOnly")]
```

Please let me know if this helps.

Thanks,
Ashish

**Comment by neil-rubens** [comment]
Thanks @ashishdhingra 

It seems that it will work; I haven't tried it yet; but it seems to work e.g. in this case: https://stackoverflow.com/a/63699403/2705777

> Hi @neil-rubens,
> 
> I came across the useful article [ASP.NET Core with AWS Lambda and Cognito](https://criticalhittech.com/2019/02/19/asp-net-core-with-aws-lambda-and-cognito/) which might be useful for configuring Cognito Group based authorization in an ASP.NET Core application. It has a section **Groups and Policies** which provides the following details to add a custom policy.
> 
> _You can use [Authorize] to ensure that only logged-in users can access the Page/Controller/Route. However you’d probably like more fine-grained control, so for that you can add users to Cognito Groups. On the ASP.NET Core app, those groups are sent as part of the user Claims. You can create authorization polices during the Startup.Configure method as follows:_
> 
> ```cs
> services.AddAuthorization(options =>
> {
>     options.AddPolicy("AdminOnly", policy =>
>     policy.RequireAssertion(context =>
>     context.User.HasClaim(c => c.Type == "cognito:groups" && c.Value == "Admin")));
> });
> ```
> 
> _This creates a policy requiring the logged in user to be part of the Cognito group Admin. To use this on a Page/Controller/Route, refer to the policy name in the Authorize attribute:_
> 
> ```cs
> [Authorize(Policy = "AdminOnly")]
> ```
> 
> Article [Now generally available: the ASP.NET Core Identity Provider for Amazon Cognito](https://aws.amazon.com/blogs/developer/now-generally-available-the-asp-net-core-identity-provider-for-amazon-cognito/) also provides similar guidance.
> 
> Please let me know if this helps.
> 
> Thanks,
> Ashish

**Comment by Renegade13Code** [comment]
I have solved the issue of [Authorize(Roles = "Admin")] not working correctly by creating a custom authorization handler and registered it in the DI container as follows:
```
public class CognitoGroupAuthorizationHandler: AuthorizationHandler<RolesAuthorizationRequirement>
{
    protected override Task HandleRequirementAsync(AuthorizationHandlerContext context, RolesAuthorizationRequirement requirement)
    {
        if (context.User.HasClaim(c => c.Type == "cognito:groups" && requirement.AllowedRoles.Contains(c.Value)))
        {
            context.Succeed(requirement);
        }
        else
        {
            context.Fail();
        }
        return Task.CompletedTask;
    }
}
```
And registration:
```
builder.Services.AddSingleton<IAuthorizationHandler, CognitoGroupAuthorizationHandler>();
```
Hope this helps :)
