### ISSUE TITLE
Manage Group of user pool

### ISSUE THREAD

**Issue by futurify-ydang** [aws/aws-aspnet-cognito-identity-provider#92]
Hi guys,

Accordingly this [doc](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-user-groups.html) I found these sentences.
![image](https://user-images.githubusercontent.com/44663784/54902716-b5371a80-4f0c-11e9-8573-a696c502eec1.png)

I want to use APIs to manage groups and users of those groups. How can i do that?
Please give me a help! Thanks

**Comment by klaytaybai** [comment]
Hi @futurify-ydang, you can use the aws-sdk-net to manage user groups.  Check out the classes in [CognitoIdentityProvider](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/CognitoIdentityProvider).  Also see https://www.nuget.org/packages/AWSSDK.CognitoIdentityProvider/

**Comment by assyadh** [comment]
Hi,

As @klaytaybai mentioned, you can use the SDK, or directly use the RoleManager from Identity.

In this library we have mapped roles to groups, so creating a new role creates a new group etc..

You can have a look at the doc here: https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/docs/7-User%20Roles.md

**Comment by futurify-ydang** [comment]
Thanks @klaytaybai  @assyadh
