### ISSUE TITLE
forgotpassword

### ISSUE THREAD

**Issue by ghendo** [aws/aws-aspnet-cognito-identity-provider#95]
What is the procedure to implement forgot password

**Comment by assyadh** [comment]
Hi.

You can find the different methods to use here:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/docs/5-User%20Management%20-%20Change%20and%20reset%20passwords.md#send-a-confirmation-token-to-a-cognitouser-to-reset-its-password

There is also an example in the sample application:

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/samples/Samples/Areas/Identity/Pages/Account/ResetPassword.cshtml.cs

H.
