### ISSUE TITLE
Help Wanted - Request Signature We Calculated Does Not Match 

### ISSUE THREAD

**Issue by biznearme** [aws/aws-aspnet-cognito-identity-provider#96]
"AWS": {
    "Region": "Value Entered is:  us-east-1",
    "UserPoolClientId": "Value Entered is: User Pool -> My Pool -> App Client Id",
    "UserPoolClientSecret": "Value Entered is: User Pool -> My Pool -> App Client Secret",
    "UserPoolId": "Value Entered is: General Settings - Pool Id"
  },
  "AllowedHosts": "*"
} Run the register postback. I get this error.

An unhandled exception occurred while processing the request.
HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) in HttpRequestMessageFactory.cs, line 539

AmazonCognitoIdentityProviderException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in HttpErrorResponseExceptionHandler.cs, line 60

I have looked pretty closely.  Can't see anything wrong with the implementation.  It seems like I have the correct credentials entered.  My next step is to download the source for this provider code and start digging through the source code.  

Before I go down that road, any suggestions would be appreciated.  Am I missing something?

**Comment by assyadh** [comment]
The values you entered look correct.

**Comment by biznearme** [comment]
When I fill out the register (new account) form and submit the form.  Occurs on page Register.cshtml.cs:
When the userManager.CreateAsync function is called.
No white spaces in the settings.

public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl = returnUrl ?? Url.Content("~/");
            if (ModelState.IsValid)
            {
                var user = _pool.GetUser(Input.UserName);
                user.Attributes.Add(CognitoAttribute.Email.AttributeName, Input.Email);
                user.Attributes.Add(CognitoAttribute.PhoneNumber.AttributeName, Input.Phone);

                var result = await _userManager.CreateAsync(user, Input.Password);

It's a brand new ASPNetCore 2.1.1 Web Application with your sample code ported in.  Not sure what AWS Cli (is installed on this dev box) has to do with this issue as that is not called during the DotNetCore code execution.  

Installed
Identity.Cognito 1.0.0
Extensions.CognitoAuthentication 1.0.3
ASPNETCore.App 2.1.1
ASPNETCore.Razor.Design 2.1.2
NETCore.App 2.1.0
VisualStudio.Web.CodeGeneration.Design 2.1.7

**Comment by biznearme** [comment]
I have not added any of the other AWS DotNet SDKs yet as this is a blank (standard DotNet Core template) project and I was first trying to get it to substitute Cognito for the normal DotNet db/authentication before adding anything else in.

**Comment by biznearme** [comment]
The code that is being executed is ported in verbatim from:
So created a brand new project, ported in "all" code/references/libraries/etc.

https://github.com/aws/aws-aspnet-cognito-identity-provider/tree/master/samples/Samples

**Comment by biznearme** [comment]
I would just like to get it to work.  I can upload the entire project for you if you like.  What I did is a newer update from your original sample project with regards to the DotNet version used.   I could simply delete the Cognito accounts and create new ones afterwords.  If we get it to work you could post this as a "new/updated" working sample for the community.

**Comment by biznearme** [comment]
I tried loading/running your Samples.sln project.  It does compile but it errors out when you try to run it. 

An unhandled exception occurred while processing the request.
UriFormatException: Invalid URI: The hostname could not be parsed.
System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)

UriFormatException: Invalid URI: The hostname could not be parsed.
System.Uri.CreateThis(string uri, bool dontEscape, UriKind uriKind)
System.Uri..ctor(string uriString)
Amazon.Runtime.ClientConfig.GetUrl(RegionEndpoint regionEndpoint, string regionEndpointServiceName, bool useHttp, bool useDualStack) in ClientConfig.cs
Amazon.Runtime.ClientConfig.DetermineServiceURL() in ClientConfig.cs
Amazon.Runtime.Internal.DefaultRetryPolicy..ctor(IClientConfig config) in DefaultRetryPolicy.cs
Amazon.Runtime.AmazonServiceClient.BuildRuntimePipeline() in AmazonServiceClient.cs

Anyway mines initializes just fine.  Only seems to have an issue with the credentials.

**Comment by biznearme** [comment]
I did put in the appsettings.json settings similar to my own project as they are missing in the sample of course.

**Comment by assyadh** [comment]
Hi,

This definitely looks like a credentials issue.

You don't need to add any other SDK, they are already referenced by the NuGet packages.


Sorry for not responding earlier, I have been pulled into various other issues.

Can you follow the instructions here: 

https://github.com/aws/aws-aspnet-cognito-identity-provider/blob/master/docs/1-Setup.md

Especially around setting up the Visual Studio Toolkit and a default AWS Profile.

While working on a development environment, the SDKs need access to credentials. This is done by setting up a profile using the AWS CLI:

https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/setup.html

https://docs.aws.amazon.com/sdk-for-net/v3/ndg/welcome.html

This is not required in a production environment as the credentials will be retrieve from the EC2 instance metadata.

Feel free to upload the project for me, I can have a look, just make sure to obfuscate any secrets.

It may work on my machine as I have the CLI installed with a default profile, I will let you know once the project is uploaded.

**Comment by biznearme** [comment]
Thanks for the reply.  I do appreciate the kind offer.  I have already moved back to Azure for this particular project.  I ran through my allocated time budget for R&D on the AWS stack and it appeared that many more hours could be burned before I even got to a productive eval stage.  Had to move on.          

 

Regards,

 

Les Baker

**Comment by assyadh** [comment]
Might be related to: https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/80
