### ISSUE TITLE
custom attributes

### ISSUE THREAD

**Issue by ghendo** [aws/aws-aspnet-cognito-identity-provider#97]
When registering a new user I wish to set a custom attribute
var user = _pool.GetUser(Input.Email);
                user.Attributes.Add(CognitoAttribute.Email.AttributeName, Input.Email);
                user.Attributes.Add(CognitoAttribute.GivenName.AttributeName, Input.GivenName);
                user.Attributes.Add(CognitoAttribute.FamilyName.AttributeName, Input.FamilyName);
                user.Attributes.Add("custom:site", "somevalue");
I have custome:site registered as a custom attribute however I get error when I run it.
"Failed to create the Cognito User : A client attempted to write unauthorized attribute"

**Comment by assyadh** [comment]
Hi,

You need to set up write permissions in your app client settings for this specific attribute. 

This is done in the AWS Console for Cognito. 

H.

**Comment by ghendo** [comment]
I have set the mutable to yes if that is whT you mean?
